In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from matplotlib import rcParams

%matplotlib inline

In [2]:
adp = pd.read_csv('Data/Ranked_adp_for_merge/adp_ranked_2013 - adp_ranked_2013 (1).csv')

In [3]:
fp = pd.read_csv('Data/clean_fp_data_merge/fp_data_cleaned_13 - fp_data_uncleaned_13 - fp_data_uncleaned_13.csv')

In [4]:
adp.shape

(320, 10)

In [5]:
fp['Player'] = fp['Player'].str.strip()

fp.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
0,1,Peyton Manning,659.0,"5,477",8.3,NaN,NaN,55.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,450.0,10.0,18.0,32.0,1.0
1,2,Drew Brees,650.0,"5,162",7.9,NaN,NaN,39.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,446.0,12.0,37.0,35.0,2.0
2,1,Jamaal Charles,259.0,"1,287",5.0,46.0,6.0,12.0,70.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,2,Matt Forte,289.0,"1,339",4.6,55.0,9.0,9.0,74.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,3,LeSean McCoy,314.0,"1,607",5.1,57.0,9.0,9.0,52.0,64.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [9]:
rwd = pd.merge(adp, fp, 
                 left_on = 'Player_Name', right_on = 'Player',
                 how = 'left')
rwd.shape

(324, 43)

In [10]:
rwd.tail(50)
#defense's are no longer in the data so we have an extra 32 missing data links

,Rank_x,Player_x,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
274,361,Eagles,Philadelphia,Philadelphia Eagles,2,474,6,Def,PHI,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,362,Vinatieri,Adam,Adam Vinatieri,5,703,27,PK,IND,16,...,10.0,15.0,4.0,34.0,34.0,NaN,NaN,NaN,NaN,104.0
276,363,Pryor,Terrelle,Terrelle Pryor,1,709,13,QB,OAK,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0
277,364,Brown,Josh,Josh Brown,7,681,29,PK,NYG,17,...,7.0,7.0,1.0,31.0,31.0,NaN,NaN,NaN,NaN,199.0
278,365,Gould,Robbie,Robbie Gould,9,709,29,PK,CHI,18,...,6.0,6.0,3.0,45.0,45.0,NaN,NaN,NaN,NaN,144.0
279,366,Hill,Stephen,Stephen Hill,15,463,20,WR,NYJ,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,276.0
280,367,Ballard,Jake,Jake Ballard,2,702,8,TE,ARI,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,357.0
281,368,Moss,Santana,Santana Moss,13,698,18,WR,WAS,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,213.5
282,369,Forbath,Kai,Kai Forbath,13,668,31,PK,WAS,19,...,10.0,4.0,1.0,26.0,26.0,NaN,NaN,NaN,NaN,241.5
283,370,Quick,Brian,Brian Quick,3,607,16,WR,STL,85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,283.0
284,373,Walker,Delanie,Delanie Walker,4,564,9,TE,TEN,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0
285,374,Collie,Austin,Austin Collie,12,639,7,WR,NEP,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,433.0
286,376,Jones,Felix,Felix Jones,4,668,11,RB,PIT,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,338.0
287,377,Jones,Marvin,Marvin Jones,7,616,5,WR,CIN,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0
288,378,Bills,Buffalo,Buffalo Bills,15,499,11,Def,BUF,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,379,Lewis,Marcedes,Marcedes Lewis,8,610,17,TE,JAC,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245.0
290,380,Henery,Alex,Alex Henery,10,665,22,PK,PHI,20,...,7.0,7.0,1.0,45.0,45.0,NaN,NaN,NaN,NaN,170.0
291,381,Brown,Donald,Donald Brown,10,635,5,RB,IND,81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.0
292,383,Tamme,Jacob,Jacob Tamme,11,654,9,TE,DEN,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,316.0
293,384,Nugent,Mike,Mike Nugent,11,694,16,PK,CIN,21,...,6.0,7.0,3.0,52.0,52.0,NaN,NaN,NaN,NaN,176.0
294,385,Cousins,Kirk,Kirk Cousins,6,666,9,QB,WAS,37,...,NaN,NaN,NaN,NaN,NaN,81.0,7.0,5.0,4.0,313.5
295,386,Kerley,Jeremy,Jeremy Kerley,8,615,17,WR,NYJ,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.0
296,387,Titans,Tennessee,Tennessee Titans,7,409,6,Def,TEN,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,388,Jets,New York,New York Jets,14,566,10,Def,NYJ,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,389,Tolbert,Mike,Mike Tolbert,2,694,11,RB,CAR,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.0
299,390,Baldwin,Doug,Doug Baldwin,1,652,6,WR,SEA,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.5
300,391,Gerhart,Toby,Toby Gerhart,3,664,15,RB,MIN,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,278.0
301,392,Tynes,Lawrence,Lawrence Tynes,12,679,13,PK,TBB,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,394,Avery,Donnie,Donnie Avery,4,687,14,WR,KCC,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.5
303,395,Jennings,Rashad,Rashad Jennings,1,673,10,RB,OAK,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.5
304,396,McCluster,Dexter,Dexter McCluster,4,607,13,WR,KCC,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,181.0
305,397,Graham,Shayne,Shayne Graham,7,660,5,PK,NOS,23,...,0.0,1.0,0.0,7.0,7.0,NaN,NaN,NaN,NaN,423.0
306,398,Avant,Jason,Jason Avant,2,676,6,WR,PHI,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224.5
307,400,Goodson,Mike,Mike Goodson,9,702,10,RB,NYJ,85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,445.0
308,401,Jenkins,A.J.,A.J. Jenkins,6,599,9,WR,KCC,93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,378.0
309,402,Toon,Nick,Nick Toon,18,692,9,WR,NOS,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441.0
310,404,Succop,Ryan,Ryan Succop,13,700,10,PK,KCC,24,...,9.0,6.0,1.0,52.0,52.0,NaN,NaN,NaN,NaN,162.5
311,405,McGahee,Willis,Willis McGahee,5,700,7,RB,CLE,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,285.0
312,406,Forsett,Justin,Justin Forsett,6,656,8,RB,JAC,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,359.0
313,407,Burleson,Nate,Nate Burleson,8,642,11,WR,DET,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,235.5
314,408,Baldwin,Jon,Jon Baldwin,11,597,10,WR,SFO,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,486.5
315,409,Gabbert,Blaine,Blaine Gabbert,5,690,6,QB,JAC,38,...,NaN,NaN,NaN,NaN,NaN,42.0,7.0,12.0,9.0,358.0
316,410,Washington,Nate,Nate Washington,3,612,10,WR,TEN,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0
317,411,Suisham,Shaun,Shaun Suisham,14,694,10,PK,PIT,25,...,13.0,8.0,0.0,39.0,39.0,NaN,NaN,NaN,NaN,141.0
318,412,Bironas,Rob,Rob Bironas,13,696,12,PK,TEN,26,...,8.0,5.0,2.0,41.0,41.0,NaN,NaN,NaN,NaN,162.5
319,413,Hankerson,Leonard,Leonard Hankerson,14,554,9,WR,WAS,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,244.0
320,414,Lloyd,Brandon,Brandon Lloyd,13,653,7,WR,FA,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,415,Chandler,Scott,Scott Chandler,8,564,7,TE,BUF,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151.0
322,416,Wright,Jarius,Jarius Wright,17,615,5,WR,MIN,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240.0
323,417,Bess,Davone,Davone Bess,7,621,6,WR,CLE,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,229.5

In [11]:
rounds_4 = rwd.head(48)
rounds_4['Position'].value_counts()

RB    23
WR    17
QB     6
TE     2
Name: Position, dtype: int64

In [13]:
first_second = rwd.iloc[0:24]
df['Position'].value_counts()

RB    15
WR     6
QB     2
TE     1
Name: Position, dtype: int64

In [18]:
first = rwd.iloc[0:12]
first['Position'].value_counts()

RB    10
QB     1
WR     1
Name: Position, dtype: int64

In [19]:
second = rwd.iloc[12:24]
second['Position'].value_counts()

WR    5
RB    5
TE    1
QB    1
Name: Position, dtype: int64

In [20]:
third = rwd.iloc[24:36]
third['Position'].value_counts()

RB    5
WR    5
QB    2
Name: Position, dtype: int64

In [21]:
fourth = rwd.iloc[36:48]
fourth['Position'].value_counts()

WR    6
RB    3
QB    2
TE    1
Name: Position, dtype: int64

In [22]:
rwd.to_csv('merged_data_13.csv', index = False)