In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from matplotlib import rcParams

%matplotlib inline

In [3]:
adp_19 = pd.read_csv('Data/Ranked_adp_for_merge/adp_ranked_2019 - adp_ranked_2019.csv')

In [4]:
fp_19 = pd.read_csv('Data/clean_fp_data_merge/fp_data_cleaned_19 - fp_data_uncleaned - fp_data_uncleaned_19.csv')

In [5]:
adp_19.head(10)

,Rank,Player,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank
0,1,Barkley,Saquon,Saquon Barkley,1,369,56,RB,NYG,1
1,2,McCaffrey,Christian,Christian McCaffrey,1,205,57,RB,CAR,2
2,3,Kamara,Alvin,Alvin Kamara,1,249,54,RB,NOS,3
3,4,Elliott,Ezekiel,Ezekiel Elliott,1,201,57,RB,DAL,4
4,5,Hopkins,DeAndre,DeAndre Hopkins,1,210,58,WR,HOU,1
5,6,Adams,Davante,Davante Adams,1,207,57,WR,GBP,2
6,7,Johnson,David,David Johnson,1,221,59,RB,ARI,5
7,8,Bell,Le'Veon,Le'Veon Bell,1,194,59,RB,NYJ,6
8,9,Thomas,Michael,Michael Thomas,1,205,59,WR,NOS,3
9,10,Conner,James,James Conner,1,259,53,RB,PIT,7

In [6]:
adp_19.shape

(323, 10)

In [19]:
fp_19['Player'] = fp_19['Player'].str.strip()

fp_19.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
0,1,Lamar Jackson,401.0,"3,127",7.8,NaN,NaN,36.0,NaN,NaN,...,6.0,23.0,176.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,Christian McCaffrey,287.0,"1,387",4.8,84.0,6.0,15.0,116.0,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,2,Dak Prescott,596.0,"4,902",8.2,NaN,NaN,30.0,NaN,NaN,...,11.0,23.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,3,Jameis Winston,626.0,"5,109",8.2,NaN,NaN,33.0,NaN,NaN,...,30.0,47.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,4,Russell Wilson,516.0,"4,110",8.0,NaN,NaN,31.0,NaN,NaN,...,5.0,48.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [8]:
lj = fp_19[fp_19['Player'] == 'Lamar Jackson']
lj.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
0,1,Lamar Jackson,401.0,"3,127",7.8,NaN,NaN,36.0,NaN,NaN,...,6.0,23.0,176.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [12]:
rwd_19 = pd.merge(adp_19, fp_19,
                 left_on = 'Player_Name', right_on = 'Player',
                 how = 'left')
rwd_19.shape

(325, 49)

In [18]:
rwd_19.tail(50)

,Rank_x,Player_x,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
275,348,Thomas,Ian,Ian Thomas,2,602,11,TE,CAR,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,394.5
276,349,Lions,Detroit,Detroit Lions,13,527,6,Def,DET,24,...,7.0,NaN,NaN,28.0,11.0,13.0,1.0,0.0,2.0,269.0
277,350,Panthers,Carolina,Carolina Panthers,4,438,7,Def,CAR,25,...,14.0,NaN,NaN,53.0,7.0,8.0,1.0,2.0,0.0,208.0
278,351,Redskins,Washington,Washington Redskins,13,499,6,Def,WAS,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,352,Gano,Graham,Graham Gano,5,850,6,PK,CAR,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,921.0
280,353,Agholor,Nelson,Nelson Agholor,4,525,21,WR,PHI,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245.0
281,354,Beasley,Cole,Cole Beasley,3,868,20,WR,BUF,85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.0
282,355,Gore,Frank,Frank Gore,3,1043,19,RB,BUF,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215.0
283,356,Yeldon,T.J.,T.J. Yeldon,6,703,16,RB,BUF,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,415.0
284,357,LaCosse,Matt,Matt LaCosse,2,1026,11,TE,NEP,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,403.0
285,358,Snead,Willie,Willie Snead,2,756,16,WR,BAL,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,239.0
286,359,Thomas,Demaryius,Demaryius Thomas,6,789,15,WR,NYJ,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,265.0
287,360,Cobb,Randall,Randall Cobb,8,826,19,WR,DAL,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.0
288,361,Higgins,Rashard,Rashard Higgins,4,811,14,WR,CLE,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,455.5
289,362,Chark,D.J.,D.J. Chark,1,582,12,WR,JAC,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0
290,363,Brate,Cameron,Cameron Brate,14,666,15,TE,TBB,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,248.0
291,364,Ross,John,John Ross,1,478,15,WR,CIN,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,235.5
292,365,Everett,Gerald,Gerald Everett,2,575,12,TE,LAR,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,252.5
293,366,Keenum,Case,Case Keenum,2,720,11,QB,WAS,38,...,5.0,15.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,172.5
294,367,Doctson,Josh,Josh Doctson,9,667,14,WR,FA,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,921.0
295,368,Dorsett,Phillip,Phillip Dorsett,4,935,11,WR,NEP,93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221.0
296,369,Burkhead,Rex,Rex Burkhead,2,895,14,RB,NEP,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216.0
297,370,Watson,Ben,Ben Watson,7,947,12,TE,FA,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,371,Gronkowski,Rob,Rob Gronkowski,10,945,12,TE,FA*,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,921.0
299,372,Moore,David,David Moore,1,600,11,WR,SEA,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0
300,373,Hill,Brian,Brian Hill,11,794,5,RB,ATL,85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,279.0
301,374,Tannehill,Ryan,Ryan Tannehill,1,780,7,QB,TEN,39,...,6.0,31.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,31.0
302,375,Smith,Jonnu,Jonnu Smith,6,627,8,TE,TEN,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,218.0
303,376,Bridgewater,Teddy,Teddy Bridgewater,5,785,6,QB,NOS,40,...,2.0,12.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,204.5
304,377,Crabtree,Michael,Michael Crabtree,5,1060,5,WR,FA,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,539.0
305,378,Hurst,Hayden,Hayden Hurst,3,720,8,TE,BAL,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,280.0
306,379,Amendola,Danny,Danny Amendola,7,1021,11,WR,DET,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166.0
307,380,McGuire,Elijah,Elijah McGuire,2,781,9,RB,FA,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,921.0
308,381,Cain,Deon,Deon Cain,5,679,8,WR,PIT,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,439.0
309,382,Kumerow,Jake,Jake Kumerow,3,956,7,WR,GBP,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,359.5
310,383,Perriman,Breshad,Breshad Perriman,5,837,8,WR,TBB,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.0
311,384,Ajayi,Jay,Jay Ajayi,2,803,7,RB,FA,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,560.5
312,385,Gallman,Wayne,Wayne Gallman,6,1029,8,RB,NYG,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,332.5
313,386,Gabriel,Taylor,Taylor Gabriel,5,783,11,WR,CHI,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242.0
314,387,Blue,Alfred,Alfred Blue,7,707,9,RB,FA,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,388,Reynolds,Josh,Josh Reynolds,10,638,9,WR,LAR,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,307.0
316,389,Uzomah,C.J.,C.J. Uzomah,7,774,8,TE,CIN,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,312.5
317,390,Seals-Jones,Ricky,Ricky Seals-Jones,9,605,7,TE,CLE,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.5
318,391,Martin,Doug,Doug Martin,8,914,7,RB,FA,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,392,Cole,Keelan,Keelan Cole,16,626,9,WR,JAC,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268.0
320,393,James,Jesse,Jesse James,7,960,6,TE,DET,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,418.0
321,394,Thomas,Jordan,Jordan Thomas,2,904,6,TE,HOU,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,586.5
322,395,Conley,Chris,Chris Conley,12,931,6,WR,JAC,103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.5
323,396,Watson,Justin,Justin Watson,17,799,5,WR,TBB,104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,352.5
324,397,Riddick,Theo,Theo Riddick,8,777,6,RB,DEN,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,921.0

In [22]:
rwd_19.head(50)

,Rank_x,Player_x,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
0,1,Barkley,Saquon,Saquon Barkley,1,369,56,RB,NYG,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0
1,2,McCaffrey,Christian,Christian McCaffrey,1,205,57,RB,CAR,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,3,Kamara,Alvin,Alvin Kamara,1,249,54,RB,NOS,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0
3,4,Elliott,Ezekiel,Ezekiel Elliott,1,201,57,RB,DAL,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0
4,5,Hopkins,DeAndre,DeAndre Hopkins,1,210,58,WR,HOU,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0
5,6,Adams,Davante,Davante Adams,1,207,57,WR,GBP,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0
6,7,Johnson,David,David Johnson,1,221,59,RB,ARI,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,144.0
7,8,Bell,Le'Veon,Le'Veon Bell,1,194,59,RB,NYJ,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.0
8,9,Thomas,Michael,Michael Thomas,1,205,59,WR,NOS,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
9,10,Conner,James,James Conner,1,259,53,RB,PIT,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.0
10,11,Jones,Julio,Julio Jones,1,247,58,WR,ATL,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0
11,12,Beckham,Odell,Odell Beckham,1,208,58,WR,CLE,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0
12,13,Gurley,Todd,Todd Gurley,1,187,60,RB,LAR,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.0
13,14,Mahomes,Patrick,Patrick Mahomes,1,250,54,QB,KCC,1,...,5.0,17.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0
14,15,Smith-Schuster,JuJu,JuJu Smith-Schuster,1,211,58,WR,PIT,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,206.0
15,16,Kelce,Travis,Travis Kelce,1,208,61,TE,KCC,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0
16,17,Cook,Dalvin,Dalvin Cook,1,216,61,RB,MIN,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0
17,18,Chubb,Nick,Nick Chubb,1,360,57,RB,CLE,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0
18,19,Mixon,Joe,Joe Mixon,1,211,61,RB,CIN,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0
19,20,Hill,Tyreek,Tyreek Hill,1,247,59,WR,KCC,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0
20,21,Jacobs,Josh,Josh Jacobs,1,361,96,RB,OAK,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.0
21,22,Fournette,Leonard,Leonard Fournette,1,241,61,RB,JAC,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0
22,23,Williams,Damien,Damien Williams,1,249,64,RB,KCC,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.0
23,24,Ertz,Zach,Zach Ertz,1,190,60,TE,PHI,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0
24,25,Thielen,Adam,Adam Thielen,1,187,62,WR,MIN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187.0
25,26,Allen,Keenan,Keenan Allen,1,192,64,WR,LAC,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0
26,27,Diggs,Stefon,Stefon Diggs,1,186,63,WR,MIN,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0
27,28,Cooper,Amari,Amari Cooper,1,206,64,WR,DAL,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0
28,29,Jones,Aaron,Aaron Jones,1,298,60,RB,GBP,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0
29,30,Kittle,George,George Kittle,1,248,62,TE,SFO,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.0
30,31,Montgomery,David,David Montgomery,1,365,94,RB,CHI,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.0
31,32,Watson,Deshaun,Deshaun Watson,1,231,59,QB,HOU,2,...,12.0,44.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
32,33,Gordon,Melvin,Melvin Gordon,1,252,58,RB,LAC,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0
33,34,Cooks,Brandin,Brandin Cooks,1,196,65,WR,LAR,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0
34,35,Freeman,Devonta,Devonta Freeman,1,253,65,RB,ATL,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0
35,36,Henry,Derrick,Derrick Henry,1,220,64,RB,TEN,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
36,37,Mack,Marlon,Marlon Mack,1,251,60,RB,IND,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.0
37,38,Hilton,T.Y.,T.Y. Hilton,1,200,63,WR,IND,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.0
38,39,Rodgers,Aaron,Aaron Rodgers,1,209,62,QB,GBP,3,...,4.0,36.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0
39,40,Edelman,Julian,Julian Edelman,1,212,66,WR,NEP,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
40,41,Woods,Robert,Robert Woods,1,213,64,WR,LAR,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.0
41,42,Michel,Sony,Sony Michel,1,255,63,RB,NEP,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0
42,43,Lockett,Tyler,Tyler Lockett,1,299,66,WR,SEA,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0
43,44,Ingram,Mark,Mark Ingram,1,265,65,RB,BAL,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.0
44,46,Golladay,Kenny,Kenny Golladay,1,330,64,WR,DET,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0
45,47,Godwin,Chris,Chris Godwin,1,231,65,WR,TBB,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0
46,48,Mayfield,Baker,Baker Mayfield,1,353,59,QB,CLE,4,...,21.0,40.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,26.0
47,50,Lindsay,Phillip,Phillip Lindsay,1,223,63,RB,DEN,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0
48,51,Ridley,Calvin,Calvin Ridley,1,367,62,WR,ATL,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.0
49,52,Kupp,Cooper,Cooper Kupp,2,227,65,WR,LAR,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0

In [17]:
rounds_4 = rwd_19.head(48)
rounds_4['Position'].value_counts()

RB    23
WR    18
QB     4
TE     3
Name: Position, dtype: int64

In [34]:
df = rwd_19.iloc[0:24]
df['Position'].value_counts()

RB    14
WR     7
TE     2
QB     1
Name: Position, dtype: int64

In [36]:
first = rwd_19.iloc[0:12]
first['Position'].value_counts()

RB    7
WR    5
Name: Position, dtype: int64

In [40]:
second = rwd_19.iloc[12:24]
second['Position'].value_counts()

RB    7
TE    2
WR    2
QB    1
Name: Position, dtype: int64

In [41]:
third = rwd_19.iloc[24:36]
third['Position'].value_counts()

RB    5
WR    5
TE    1
QB    1
Name: Position, dtype: int64

In [42]:
fourth = rwd_19.iloc[36:48]
fourth['Position'].value_counts()

WR    6
RB    4
QB    2
Name: Position, dtype: int64

In [44]:
rwd_19.to_csv('merged_data_19.csv', index = False)