In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from matplotlib import rcParams

%matplotlib inline

In [40]:
adp_19 = pd.read_csv('Ranked_adp_for_merge/adp_ranked_2019 - adp_ranked_2019.csv')
fp_19 = pd.read_csv('clean_fp_data_merge/fp_data_cleaned_19 - fp_data_uncleaned - fp_data_uncleaned_19.csv')

In [41]:
adp_19.head(10)

,Rank,Player,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank
0,1,Barkley,Saquon,Saquon Barkley,1,369,56,RB,NYG,1
1,2,McCaffrey,Christian,Christian McCaffrey,1,205,57,RB,CAR,2
2,3,Kamara,Alvin,Alvin Kamara,1,249,54,RB,NOS,3
3,4,Elliott,Ezekiel,Ezekiel Elliott,1,201,57,RB,DAL,4
4,5,Hopkins,DeAndre,DeAndre Hopkins,1,210,58,WR,HOU,1
5,6,Adams,Davante,Davante Adams,1,207,57,WR,GBP,2
6,7,Johnson,David,David Johnson,1,221,59,RB,ARI,5
7,8,Bell,Le'Veon,Le'Veon Bell,1,194,59,RB,NYJ,6
8,9,Thomas,Michael,Michael Thomas,1,205,59,WR,NOS,3
9,10,Conner,James,James Conner,1,259,53,RB,PIT,7

In [42]:
adp_19.shape

(323, 10)

In [43]:
fp_19['Player'] = fp_19['Player'].str.strip()

fp_19.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
0,1,Lamar Jackson,401.0,"3,127",7.8,NaN,NaN,36.0,NaN,NaN,...,6.0,23.0,176.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,Christian McCaffrey,287.0,"1,387",4.8,84.0,6.0,15.0,116.0,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,2,Dak Prescott,596.0,"4,902",8.2,NaN,NaN,30.0,NaN,NaN,...,11.0,23.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,3,Jameis Winston,626.0,"5,109",8.2,NaN,NaN,33.0,NaN,NaN,...,30.0,47.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,4,Russell Wilson,516.0,"4,110",8.0,NaN,NaN,31.0,NaN,NaN,...,5.0,48.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [44]:
fp_19['Player'] = fp_19['Player'].str.strip(' II')
#fp_19['Player'] = fp_19['Player'].str.strip(' Jr.')

In [45]:
lj = fp_19[fp_19['Player'] == 'Lamar Jackson']
lj.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
0,1,Lamar Jackson,401.0,"3,127",7.8,NaN,NaN,36.0,NaN,NaN,...,6.0,23.0,176.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [46]:
fp_19.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
0,1,Lamar Jackson,401.0,"3,127",7.8,NaN,NaN,36.0,NaN,NaN,...,6.0,23.0,176.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,Christian McCaffrey,287.0,"1,387",4.8,84.0,6.0,15.0,116.0,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,2,Dak Prescott,596.0,"4,902",8.2,NaN,NaN,30.0,NaN,NaN,...,11.0,23.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,3,Jameis Winston,626.0,"5,109",8.2,NaN,NaN,33.0,NaN,NaN,...,30.0,47.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,4,Russell Wilson,516.0,"4,110",8.0,NaN,NaN,31.0,NaN,NaN,...,5.0,48.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [47]:
rwd_19 = pd.merge(fp_19, adp_19,
                 left_on = 'Player', right_on = 'Player_Name',
                 how = 'right')
rwd_19.shape

(325, 49)

In [48]:
lwd_19 = pd.merge(fp_19, adp_19,
                 left_on = 'Player', right_on = 'Player_Name')
lwd_19.shape

(308, 49)

In [49]:
rwd_19.head(100)

,Rank_x,Player_x,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,Rank_y,Player_y,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank
0,1.0,Lamar Jackson,401.0,"3,127",7.8,NaN,NaN,36.0,NaN,NaN,...,154,Jackson,Lamar,Lamar Jackson,1,313,63,QB,BAL,18
1,1.0,Christian McCaffrey,287.0,"1,387",4.8,84.0,6.0,15.0,116.0,142.0,...,2,McCaffrey,Christian,Christian McCaffrey,1,205,57,RB,CAR,2
2,2.0,Dak Prescott,596.0,"4,902",8.2,NaN,NaN,30.0,NaN,NaN,...,153,Prescott,Dak,Dak Prescott,1,318,62,QB,DAL,17
3,3.0,Jameis Winston,626.0,"5,109",8.2,NaN,NaN,33.0,NaN,NaN,...,126,Winston,Jameis,Jameis Winston,2,358,62,QB,TBB,15
4,4.0,Russell Wilson,516.0,"4,110",8.0,NaN,NaN,31.0,NaN,NaN,...,67,Wilson,Russell,Russell Wilson,1,225,65,QB,SEA,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,26.0,Ronald Jones,172.0,724,4.2,49.0,6.0,6.0,31.0,40.0,...,226,Jones,Ronald,Ronald Jones,2,384,48,RB,TBB,56
96,27.0,Carlos Hyde,245.0,"1,070",4.4,58.0,8.0,6.0,10.0,16.0,...,270,Hyde,Carlos,Carlos Hyde,1,584,42,RB,HOU,64
97,28.0,Sony Michel,247.0,912,3.7,26.0,3.0,7.0,12.0,20.0,...,42,Michel,Sony,Sony Michel,1,255,63,RB,NEP,21
98,5.0,Los Angeles Rams,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,175,Rams,Los Angeles,Los Angeles Rams,3,413,53,Def,LAR,2
99,35.0,Darius Slayton,0.0,740,NaN,55.0,12.0,8.0,48.0,84.0,...,230,Slayton,Darius,Darius Slayton,3,686,14,WR,NYG,63

In [50]:
rwd_19.tail(60)

,Rank_x,Player_x,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,Rank_y,Player_y,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank
265,49.0,Josh Rosen,109.0,567,5.2,NaN,NaN,1.0,NaN,NaN,...,317,Rosen,Josh,Josh Rosen,4,726,13,QB,MIA,35
266,95.0,Travis Homer,18.0,114,6.3,29.0,1.0,0.0,11.0,13.0,...,273,Homer,Travis,Travis Homer,3,1021,10,RB,SEA,65
267,63.0,Jesse James,0.0,142,NaN,23.0,1.0,0.0,16.0,27.0,...,393,James,Jesse,Jesse James,7,960,6,TE,DET,38
268,52.0,Cam Newton,89.0,572,6.4,NaN,NaN,0.0,NaN,NaN,...,98,Newton,Cam,Cam Newton,1,373,64,QB,CAR,13
269,146.0,Deon Cain,0.0,124,NaN,35.0,3.0,0.0,9.0,20.0,...,381,Cain,Deon,Deon Cain,5,679,8,WR,PIT,97
270,75.0,Trey Burton,0.0,84,NaN,16.0,0.0,0.0,14.0,24.0,...,227,Burton,Trey,Trey Burton,1,463,50,TE,CHI,19
271,150.0,Rashard Higgins,0.0,55,NaN,35.0,1.0,1.0,4.0,11.0,...,361,Higgins,Rashard,Rashard Higgins,4,811,14,WR,CLE,89
272,82.0,David Njoku,0.0,41,NaN,18.0,0.0,1.0,5.0,10.0,...,130,Njoku,David,David Njoku,1,461,62,TE,CLE,12
273,158.0,Robert Foster,2.0,64,NaN,24.0,3.0,0.0,3.0,18.0,...,345,Foster,Robert,Robert Foster,1,546,12,WR,BUF,82
274,161.0,Riley Ridley,0.0,69,NaN,32.0,1.0,0.0,6.0,7.0,...,118,Ridley,Riley,Riley Ridley,1,613,25,WR,CHI,42
275,115.0,Mike Davis,13.0,27,2.1,8.0,0.0,0.0,7.0,8.0,...,341,Davis,Mike,Mike Davis,1,705,21,RB,CAR,81
276,121.0,Devine Ozigbo,9.0,27,3.0,9.0,0.0,0.0,3.0,5.0,...,203,Ozigbo,Devine,Devine Ozigbo,9,843,17,RB,JAC,52
277,96.0,Drew Sample,0.0,30,NaN,21.0,1.0,0.0,5.0,6.0,...,236,Sample,Drew,Drew Sample,6,812,9,TE,CIN,20
278,58.0,Will Grier,52.0,228,4.4,NaN,NaN,0.0,NaN,NaN,...,162,Grier,Will,Will Grier,3,726,20,QB,CAR,19
279,124.0,C.J. Anderson,16.0,43,2.7,9.0,0.0,0.0,0.0,0.0,...,313,Anderson,C.J.,C.J. Anderson,2,479,36,RB,FA,73
280,183.0,Michael Crabtree,0.0,22,NaN,9.0,0.0,0.0,4.0,5.0,...,377,Crabtree,Michael,Michael Crabtree,5,1060,5,WR,FA,95
281,187.0,Donte Moncrief,0.0,18,NaN,11.0,0.0,0.0,4.0,15.0,...,204,Moncrief,Donte,Donte Moncrief,1,693,60,WR,FA,58
282,190.0,Chris Moore,1.0,21,NaN,13.0,0.0,0.0,3.0,5.0,...,269,Moore,Chris,Chris Moore,1,879,30,WR,BAL,69
283,193.0,Stanley Morgan,0.0,18,NaN,9.0,0.0,0.0,3.0,10.0,...,321,Morgan,Stanley,Stanley Morgan,1,1213,5,WR,CIN,77
284,130.0,Jay Ajayi,10.0,30,3.0,11.0,0.0,0.0,0.0,1.0,...,384,Ajayi,Jay,Jay Ajayi,2,803,7,RB,FA,87
285,111.0,Jordan Thomas,0.0,8,NaN,8.0,0.0,0.0,1.0,3.0,...,394,Thomas,Jordan,Jordan Thomas,2,904,6,TE,HOU,39
286,137.0,Damien Harris,4.0,12,3.0,13.0,0.0,0.0,0.0,0.0,...,129,Harris,Damien,Damien Harris,3,717,59,RB,NEP,33
287,139.0,Dexter Williams,5.0,11,2.2,5.0,0.0,0.0,0.0,0.0,...,157,Williams,Dexter,Dexter Williams,1,719,29,RB,GBP,42
288,142.0,Jordan Scarlett,4.0,9,2.3,6.0,0.0,0.0,0.0,0.0,...,267,Scarlett,Jordan,Jordan Scarlett,9,918,15,RB,CAR,63
289,170.0,Jace Sternberger,0.0,0,NaN,0.0,0.0,0.0,0.0,1.0,...,91,Sternberger,Jace,Jace Sternberger,1,607,30,TE,GBP,8
290,168.0,Kahale Warring,0.0,0,NaN,0.0,0.0,0.0,0.0,0.0,...,145,Warring,Kahale,Kahale Warring,9,671,19,TE,HOU,13
291,151.0,Trayveon Williams,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,174,Williams,Trayveon,Trayveon Williams,8,795,21,RB,CIN,45
292,156.0,Damarea Crockett,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,298,Crockett,Damarea,Damarea Crockett,2,985,13,RB,GBP,69
293,157.0,Mike Weber,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,207,Weber,Mike,Mike Weber,6,817,14,RB,FA,53
294,76.0,Giorgio Tavecchio,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,316,Tavecchio,Giorgio,Giorgio Tavecchio,8,700,18,PK,FA,14
295,71.0,Graham Gano,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,352,Gano,Graham,Graham Gano,5,850,6,PK,CAR,23
296,207.0,Rob Gronkowski,0.0,0,NaN,0.0,0.0,0.0,0.0,0.0,...,371,Gronkowski,Rob,Rob Gronkowski,10,945,12,TE,FA*,33
297,243.0,Emanuel Hall,0.0,0,NaN,0.0,0.0,0.0,0.0,0.0,...,219,Hall,Emanuel,Emanuel Hall,13,993,8,WR,WAS,62
298,241.0,Hakeem Butler,0.0,0,NaN,0.0,0.0,0.0,0.0,0.0,...,68,Butler,Hakeem,Hakeem Butler,1,672,32,WR,ARI,26
299,127.0,Hakeem Butler,0.0,0,NaN,0.0,0.0,0.0,0.0,0.0,...,68,Butler,Hakeem,Hakeem Butler,1,672,32,WR,ARI,26
300,272.0,Theo Riddick,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,397,Riddick,Theo,Theo Riddick,8,777,6,RB,DEN,91
301,224.0,Lil'Jordan Humphrey,0.0,0,NaN,0.0,0.0,0.0,0.0,1.0,...,305,Humphrey,Lil'Jordan,Lil'Jordan Humphrey,23,1117,5,WR,NOS,75
302,230.0,D'Onta Foreman,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,286,Foreman,D'Onta,D'Onta Foreman,7,842,11,RB,FA,66
303,423.0,Josh Doctson,0.0,0,NaN,0.0,0.0,0.0,0.0,0.0,...,367,Doctson,Josh,Josh Doctson,9,667,14,WR,FA,92
304,200.0,Elijah Holyfield,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,255,Holyfield,Elijah,Elijah Holyfield,6,947,10,RB,PHI,60
305,193.0,Elijah McGuire,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,380,McGuire,Elijah,Elijah McGuire,2,781,9,RB,FA,86
306,381.0,A.J. Green,0.0,0,NaN,0.0,0.0,0.0,0.0,0.0,...,65,Green,A.J.,A.J. Green,2,275,66,WR,CIN,25
307,140.0,Jarrett Stidham,4.0,14,3.5,NaN,NaN,0.0,NaN,NaN,...,186,Stidham,Jarrett,Jarrett Stidham,4,774,17,QB,NEP,22
308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88,Smith Jr.,Irv,Irv Smith Jr.,2,605,36,TE,MIN,7
309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,109,Metcalf,DK,DK Metcalf,1,367,81,WR,SEA,38
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,132,Anderson,Rodney,Rodney Anderson,5,722,23,RB,CIN,34
311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,192,Williams,James,James Williams,6,829,10,RB,FA,49
312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,199,Anderson,Bruce,Bruce Anderson,3,1161,18,RB,IND,51
313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,249,Barnes,Alex,Alex Barnes,10,1030,10,RB,FA,58
314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,260,Smith,Ito,Ito Smith,1,631,47,RB,ATL,61
315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,297,Higdon,Karan,Karan Higdon,13,1042,8,RB,HOU,68
316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,304,Ginn Jr.,Ted,Ted Ginn Jr.,1,1085,36,WR,NOS,74
317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,318,Badgley,Mike,Mike Badgley,8,699,30,PK,LAC,15
318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,324,Colts,Indianapolis,Indianapolis Colts,8,345,13,Def,IND,21
319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,333,Hauschka,Steven,Steven Hauschka,8,820,9,PK,BUF,18
320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,348,Thomas,Ian,Ian Thomas,2,602,11,TE,CAR,28
321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,351,Redskins,Washington,Washington Redskins,13,499,6,Def,WAS,26
322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,370,Watson,Ben,Ben Watson,7,947,12,TE,FA,32
323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,387,Blue,Alfred,Alfred Blue,7,707,9,RB,FA,89
324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,391,Martin,Doug,Doug Martin,8,914,7,RB,FA,90

In [39]:
rwd_19.head(15)

,Rank_x,Player_x,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,Rank_y,Player_y,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank
0,1.0,Lamar Jackson,401.0,"3,127",7.8,NaN,NaN,36.0,NaN,NaN,...,154,Jackson,Lamar,Lamar Jackson,1,313,63,QB,BAL,18
1,1.0,Christian McCaffrey,287.0,"1,387",4.8,84.0,6.0,15.0,116.0,142.0,...,2,McCaffrey,Christian,Christian McCaffrey,1,205,57,RB,CAR,2
2,2.0,Dak Prescott,596.0,"4,902",8.2,NaN,NaN,30.0,NaN,NaN,...,153,Prescott,Dak,Dak Prescott,1,318,62,QB,DAL,17
3,3.0,Jameis Winston,626.0,"5,109",8.2,NaN,NaN,33.0,NaN,NaN,...,126,Winston,Jameis,Jameis Winston,2,358,62,QB,TBB,15
4,4.0,Russell Wilson,516.0,"4,110",8.0,NaN,NaN,31.0,NaN,NaN,...,67,Wilson,Russell,Russell Wilson,1,225,65,QB,SEA,7
5,5.0,Deshaun Watson,495.0,"3,852",7.8,NaN,NaN,26.0,NaN,NaN,...,32,Watson,Deshaun,Deshaun Watson,1,231,59,QB,HOU,2
6,1.0,Michael Thomas,1.0,"1,725",NaN,49.0,17.0,9.0,149.0,185.0,...,9,Thomas,Michael,Michael Thomas,1,205,59,WR,NOS,3
7,6.0,Josh Allen,461.0,"3,089",6.7,NaN,NaN,20.0,NaN,NaN,...,213,Allen,Josh,Josh Allen,1,445,49,QB,BUF,25
8,7.0,Kyler Murray,542.0,"3,722",6.9,NaN,NaN,20.0,NaN,NaN,...,76,Murray,Kyler,Kyler Murray,1,368,91,QB,ARI,9
9,8.0,Patrick Mahomes,484.0,"4,031",8.3,NaN,NaN,26.0,NaN,NaN,...,14,Mahomes,Patrick,Patrick Mahomes,1,250,54,QB,KCC,1
10,2.0,Aaron Jones,236.0,"1,084",4.6,56.0,5.0,16.0,49.0,68.0,...,29,Jones,Aaron,Aaron Jones,1,298,60,RB,GBP,15
11,3.0,Derrick Henry,303.0,"1,540",5.1,74.0,9.0,16.0,18.0,24.0,...,36,Henry,Derrick,Derrick Henry,1,220,64,RB,TEN,19
12,4.0,Ezekiel Elliott,301.0,"1,357",4.5,33.0,4.0,12.0,54.0,71.0,...,4,Elliott,Ezekiel,Ezekiel Elliott,1,201,57,RB,DAL,4
13,9.0,Carson Wentz,607.0,"4,039",6.7,NaN,NaN,27.0,NaN,NaN,...,63,Wentz,Carson,Carson Wentz,1,196,64,QB,PHI,6
14,10.0,Aaron Rodgers,569.0,"4,002",7.0,NaN,NaN,26.0,NaN,NaN,...,39,Rodgers,Aaron,Aaron Rodgers,1,209,62,QB,GBP,3

In [25]:
adp_19.shape

(323, 10)

In [15]:
fp_19.shape

(1234, 39)

In [16]:
#use this for corr