In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from matplotlib import rcParams

%matplotlib inline

In [2]:
adp = pd.read_csv('Data/Ranked_adp_for_merge/adp_ranked_2014 - adp_ranked_2014.csv')

In [3]:
fp = pd.read_csv('Data/clean_fp_data_merge/fp_data_cleaned_14 - fp_data_uncleaned_14 - fp_data_uncleaned_14.csv')

In [4]:
adp.shape

(343, 10)

In [5]:
fp['Player'] = fp['Player'].str.strip()

fp.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
0,1,Antonio Brown,4.0,"1,698",NaN,63.0,19.0,13.0,129.0,181.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,Le'Veon Bell,290.0,"1,361",4.7,81.0,8.0,8.0,83.0,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,1,Aaron Rodgers,520.0,"4,381",8.4,NaN,NaN,38.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,341.0,5.0,28.0,43.0,3.0
3,2,DeMarco Murray,392.0,"1,845",4.7,51.0,15.0,13.0,57.0,64.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,2,Andrew Luck,616.0,"4,761",7.7,NaN,NaN,40.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,380.0,16.0,27.0,64.0,5.0

In [8]:
rwd = pd.merge(adp, fp, 
                 left_on = 'Player_Name', right_on = 'Player',
                 how = 'left')
rwd.shape

(346, 43)

In [9]:
rwd.tail(50)
#defense's are no longer in the data so we have an extra 32 missing data links

,Rank_x,Player_x,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
296,379,Celek,Brent,Brent Celek,2,637,11,TE,PHI,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,257.0
297,380,Robinson,Adrien,Adrien Robinson,24,698,5,TE,NYG,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,420.0
298,381,Taylor,Stepfan,Stepfan Taylor,20,649,11,RB,ARI,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.5
299,382,Moore,Denarius,Denarius Moore,1,645,14,WR,OAK,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.5
300,383,Henery,Alex,Alex Henery,24,712,23,PK,FA*,20,...,0.0,0.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,511.0
301,384,Toilolo,Levine,Levine Toilolo,7,662,14,TE,ATL,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.0
302,385,Vikings,Minnesota,Minnesota Vikings,19,514,12,Def,MIN,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,386,Folk,Nick,Nick Folk,18,638,24,PK,NYJ,21,...,7.0,9.0,3.0,23.0,23.0,NaN,NaN,NaN,NaN,172.0
304,387,Vick,Michael,Michael Vick,5,815,11,QB,NYJ,41,...,NaN,NaN,NaN,NaN,NaN,64.0,2.0,19.0,26.0,320.0
305,388,Caldwell,Andre,Andre Caldwell,5,885,5,WR,DEN,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,467.0
306,389,Polk,Chris,Chris Polk,4,662,9,RB,PHI,85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,316.0
307,390,Dolphins,Miami,Miami Dolphins,6,511,16,Def,MIA,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,391,Rogers,Da'Rick,Da'Rick Rogers,3,782,8,WR,KCC,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,392,Suisham,Shaun,Shaun Suisham,13,807,23,PK,PIT,22,...,6.0,10.0,1.0,45.0,45.0,NaN,NaN,NaN,NaN,138.0
310,393,Daniels,Owen,Owen Daniels,2,896,5,TE,BAL,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,148.0
311,394,Gresham,Jermaine,Jermaine Gresham,9,643,7,TE,CIN,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129.0
312,395,Henne,Chad,Chad Henne,6,821,5,QB,JAC,42,...,NaN,NaN,NaN,NaN,NaN,42.0,1.0,16.0,4.0,346.0
313,396,Carpenter,Dan,Dan Carpenter,26,838,20,PK,BUF,23,...,12.0,7.0,6.0,31.0,32.0,NaN,NaN,NaN,NaN,140.5
314,397,Barth,Connor,Connor Barth,2,828,6,PK,DEN,24,...,5.0,3.0,1.0,15.0,15.0,NaN,NaN,NaN,NaN,282.0
315,398,Jernigan,Jerrel,Jerrel Jernigan,5,795,6,WR,NYG,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,466.0
316,399,Nugent,Mike,Mike Nugent,17,808,16,PK,CIN,25,...,10.0,10.0,0.0,39.0,39.0,NaN,NaN,NaN,NaN,174.5
317,400,Lewis,Marcedes,Marcedes Lewis,25,728,13,TE,JAC,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.0
318,401,Redskins,Washington,Washington Redskins,23,538,6,Def,WAS,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,402,Quick,Brian,Brian Quick,6,708,7,WR,STL,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,232.0
320,403,Cousins,Kirk,Kirk Cousins,1,823,6,QB,WAS,43,...,NaN,NaN,NaN,NaN,NaN,126.0,9.0,8.0,7.0,214.0
321,404,Brown,Marlon,Marlon Brown,12,668,10,WR,BAL,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0
322,405,Chargers,San Diego,San Diego Chargers,15,479,9,Def,SDC,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,406,Green-Ellis,BenJarvus,BenJarvus Green-Ellis,14,717,6,RB,FA*,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,407,Gano,Graham,Graham Gano,17,814,18,PK,CAR,26,...,12.0,9.0,1.0,34.0,34.0,NaN,NaN,NaN,NaN,165.5
325,408,Rainey,Bobby,Bobby Rainey,3,759,6,RB,TBB,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.0
326,409,Todman,Jordan,Jordan Todman,14,681,7,RB,JAC,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.0
327,410,Escobar,Gavin,Gavin Escobar,8,680,5,TE,DAL,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,319.0
328,411,Tolbert,Mike,Mike Tolbert,4,734,7,RB,CAR,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.0
329,412,Succop,Ryan,Ryan Succop,1,813,16,PK,TEN,27,...,7.0,5.0,2.0,27.0,27.0,NaN,NaN,NaN,NaN,228.5
330,413,Bostick,Brandon,Brandon Bostick,15,887,5,TE,GBP,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,477.5
331,414,Moore,Lance,Lance Moore,12,684,6,WR,PIT,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.0
332,415,Fauria,Joseph,Joseph Fauria,25,823,6,TE,DET,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.0
333,416,Washington,Nate,Nate Washington,8,664,8,WR,TEN,103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161.0
334,417,Bailey,Stedman,Stedman Bailey,29,785,5,WR,STL,104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,230.5
335,418,Titans,Tennessee,Tennessee Titans,23,504,10,Def,TEN,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,419,Jaguars,Jacksonville,Jacksonville Jaguars,11,670,6,Def,JAC,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,420,Rivera,Mychal,Mychal Rivera,26,674,7,TE,OAK,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133.5
338,421,Chandler,Scott,Scott Chandler,26,806,6,TE,BUF,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.0
339,422,Finley,Jermichael,Jermichael Finley,35,700,5,TE,FA*,44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,423,Feely,Jay,Jay Feely,39,818,10,PK,CHI,28,...,1.0,1.0,0.0,5.0,5.0,NaN,NaN,NaN,NaN,448.0
341,424,Sturgis,Caleb,Caleb Sturgis,13,817,11,PK,MIA,29,...,7.0,6.0,3.0,41.0,41.0,NaN,NaN,NaN,NaN,155.0
342,425,Brown,Josh,Josh Brown,35,844,8,PK,NYG,30,...,9.0,4.0,4.0,44.0,44.0,NaN,NaN,NaN,NaN,168.5
343,426,Hill,Stephen,Stephen Hill,14,862,5,WR,CAR,105,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,427,Forbath,Kai,Kai Forbath,37,870,5,PK,WAS,31,...,6.0,7.0,0.0,31.0,31.0,NaN,NaN,NaN,NaN,191.5
345,428,Kerley,Jeremy,Jeremy Kerley,5,680,5,WR,NYJ,106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,207.0

In [10]:
rounds_4 = rwd.head(48)
rounds_4['Position'].value_counts()

WR    21
RB    19
QB     5
TE     3
Name: Position, dtype: int64

In [11]:
df = rwd.iloc[0:24]
df['Position'].value_counts()

RB    11
WR     9
QB     3
TE     1
Name: Position, dtype: int64

In [12]:
first = rwd.iloc[0:12]
first['Position'].value_counts()

WR    5
RB    5
QB    1
TE    1
Name: Position, dtype: int64

In [13]:
second = rwd.iloc[12:24]
second['Position'].value_counts()

RB    6
WR    4
QB    2
Name: Position, dtype: int64

In [14]:
third = rwd.iloc[24:36]
third['Position'].value_counts()

WR    4
RB    4
QB    2
TE    2
Name: Position, dtype: int64

In [15]:
fourth = rwd.iloc[36:48]
fourth['Position'].value_counts()

WR    8
RB    4
Name: Position, dtype: int64

In [16]:
rwd.to_csv('merged_data_14.csv', index = False)