In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from matplotlib import rcParams

%matplotlib inline

In [2]:
adp = pd.read_csv('Data/Ranked_adp_for_merge/adp_ranked_2015 - adp_ranked_2015.csv')

In [3]:
fp = pd.read_csv('Data/clean_fp_data_merge/fp_data_cleaned_15 - fp_data_uncleaned_15 - fp_data_uncleaned_15.csv')

In [4]:
adp.shape

(358, 10)

In [5]:
fp['Player'] = fp['Player'].str.strip()

fp.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
0,1,Cam Newton,495.0,"3,837",7.8,NaN,NaN,35.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,296.0,10.0,33.0,132.0,1.0
1,2,Tom Brady,624.0,"4,770",7.6,NaN,NaN,36.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,402.0,7.0,38.0,34.0,2.0
2,3,Russell Wilson,483.0,"4,024",8.3,NaN,NaN,34.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,329.0,8.0,45.0,103.0,3.0
3,4,Blake Bortles,606.0,"4,428",7.3,NaN,NaN,35.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,355.0,18.0,51.0,52.0,4.0
4,1,Antonio Brown,3.0,"1,834",NaN,59.0,25.0,10.0,136.0,193.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [8]:
rwd = pd.merge(adp, fp, 
                 left_on = 'Player_Name', right_on = 'Player',
                 how = 'left')
rwd.shape

(362, 43)

In [9]:
rwd.tail(50)
#defense's are no longer in the data so we have an extra 32 missing data links

,Rank_x,Player_x,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
312,405,Taliaferro,Lorenzo,Lorenzo Taliaferro,13,592,21,RB,BAL,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,428.0
313,406,Browns,Cleveland,Cleveland Browns,8,437,28,Def,CLE,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,407,Brown,Corey,Corey Brown,10,680,8,WR,CAR,103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,408,Suisham,Shaun,Shaun Suisham,3,926,6,PK,PIT,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,409,Rice,Ray,Ray Rice,4,661,13,RB,FA*,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,411,Bullock,Randy,Randy Bullock,2,673,9,PK,NYJ,28,...,6.0,8.0,0.0,22.0,25.0,NaN,NaN,NaN,NaN,208.0
318,412,Williams,Damien,Damien Williams,3,894,10,RB,MIA,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,324.0
319,413,Cook,Jared,Jared Cook,8,618,27,TE,STL,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,244.0
320,414,Aiken,Kamar,Kamar Aiken,1,631,10,WR,BAL,104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0
321,415,Smith,Geno,Geno Smith,11,914,13,QB,NYJ,39,...,NaN,NaN,NaN,NaN,NaN,27.0,1.0,3.0,2.0,394.5
322,416,Pryor,Terrelle,Terrelle Pryor,3,1045,5,WR,CLE,105,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1022.0
323,417,Kearse,Jermaine,Jermaine Kearse,2,816,7,WR,SEA,106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.5
324,418,Chandler,Scott,Scott Chandler,11,691,10,TE,NEP,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,263.0
325,419,Asiata,Matt,Matt Asiata,6,759,10,RB,MIN,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326.0
326,420,Wilson,Albert,Albert Wilson,14,1038,10,WR,KCC,107,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.0
327,421,Rivera,Mychal,Mychal Rivera,15,950,19,TE,OAK,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,281.0
328,423,Redskins,Washington,Washington Redskins,10,508,7,Def,WAS,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,425,Bailey,Stedman,Stedman Bailey,31,665,14,WR,STL,108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,343.0
330,426,Turbin,Robert,Robert Turbin,13,886,11,RB,DAL,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.5
331,427,Manziel,Johnny,Johnny Manziel,5,770,10,QB,CLE,40,...,NaN,NaN,NaN,NaN,NaN,129.0,5.0,19.0,37.0,185.0
332,428,Housler,Robert,Robert Housler,11,837,9,TE,CHI,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,429,Tamme,Jacob,Jacob Tamme,4,920,10,TE,ATL,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172.0
334,430,Woods,Robert,Robert Woods,6,941,14,WR,BUF,109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187.5
335,431,Buccaneers,Tampa Bay,Tampa Bay Buccaneers,8,476,22,Def,TBB,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,432,Giants,New York,New York Giants,19,446,21,Def,NYG,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,433,Sanchez,Mark,Mark Sanchez,2,773,11,QB,PHI,41,...,NaN,NaN,NaN,NaN,NaN,59.0,4.0,9.0,6.0,329.0
338,434,Richardson,Trent,Trent Richardson,11,1070,10,RB,FA*,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,435,Raiders,Oakland,Oakland Raiders,14,566,6,Def,OAK,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,436,Mallett,Ryan,Ryan Mallett,7,1015,6,QB,BAL,42,...,NaN,NaN,NaN,NaN,NaN,136.0,6.0,6.0,5.0,238.0
341,437,McCown,Josh,Josh McCown,2,891,6,QB,CLE,43,...,NaN,NaN,NaN,NaN,NaN,186.0,4.0,23.0,20.0,113.0
342,438,Falcons,Atlanta,Atlanta Falcons,13,424,15,Def,ATL,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,439,Chargers,San Diego,San Diego Chargers,21,473,18,Def,SDC,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,440,Bears,Chicago,Chicago Bears,7,506,13,Def,CHI,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,441,Jennings,Greg,Greg Jennings,13,906,13,WR,MIA,110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,318.0
346,442,Jaguars,Jacksonville,Jacksonville Jaguars,30,508,18,Def,JAC,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,443,Paul,Niles,Niles Paul,16,681,10,TE,WAS,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,444,Saints,New Orleans,New Orleans Saints,23,378,13,Def,NOS,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,445,Hartline,Brian,Brian Hartline,8,681,8,WR,CLE,111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,206.0
350,446,Gillmore,Crockett,Crockett Gillmore,6,816,6,TE,BAL,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,212.0
351,447,Carey,Ka'Deem,Ka'Deem Carey,17,870,7,RB,CHI,93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,320.0
352,448,Titans,Tennessee,Tennessee Titans,24,398,8,Def,TEN,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,449,Thomas,Pierre,Pierre Thomas,14,880,5,RB,WAS,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399.0
354,450,Hawkins,Andrew,Andrew Hawkins,12,896,13,WR,CLE,112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.5
355,451,Brown,Marlon,Marlon Brown,7,766,6,WR,BAL,113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,410.0
356,452,Bradshaw,Ahmad,Ahmad Bradshaw,25,764,5,RB,IND,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,312.0
357,453,Dobson,Aaron,Aaron Dobson,18,982,7,WR,NEP,114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,391.0
358,454,Cadet,Travaris,Travaris Cadet,2,771,7,RB,NOS,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315.0
359,455,Stacy,Zac,Zac Stacy,1,875,7,RB,NYJ,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,368.5
360,456,Douglas,Harry,Harry Douglas,3,921,6,WR,TEN,115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242.0
361,457,Escobar,Gavin,Gavin Escobar,14,666,6,TE,DAL,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,436.5

In [10]:
rounds_4 = rwd.head(48)
rounds_4['Position'].value_counts()

RB    22
WR    21
QB     3
TE     2
Name: Position, dtype: int64

In [11]:
df = rwd.iloc[0:24]
df['Position'].value_counts()

RB    11
WR    10
QB     2
TE     1
Name: Position, dtype: int64

In [12]:
first = rwd.iloc[0:12]
first['Position'].value_counts()

RB    6
WR    4
QB    1
TE    1
Name: Position, dtype: int64

In [13]:
second = rwd.iloc[12:24]
second['Position'].value_counts()

WR    6
RB    5
QB    1
Name: Position, dtype: int64

In [14]:
third = rwd.iloc[24:36]
third['Position'].value_counts()

WR    6
RB    5
TE    1
Name: Position, dtype: int64

In [15]:
fourth = rwd.iloc[36:48]
fourth['Position'].value_counts()

RB    6
WR    5
QB    1
Name: Position, dtype: int64

In [16]:
rwd.to_csv('merged_data_15.csv', index = False)