In [1]:
import pandas as pd

import gc # To collect garbage values generated during running

import matplotlib.pyplot as plt

import numpy as np

import seaborn as sns

In [3]:
d = pd.read_csv('2018_cleaned_with_rounds.csv')

In [4]:
d.head(60)

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
0,1,Bell,Le'Veon,Le'Veon Bell,1,1,193,66,RB,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,933.0
1,2,Elliott,Ezekiel,Ezekiel Elliott,1,1,186,67,RB,DAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0
2,3,Johnson,David,David Johnson,1,1,198,65,RB,ARI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0
3,4,Barkley,Saquon,Saquon Barkley,1,1,451,95,RB,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
4,5,Brown,Antonio,Antonio Brown,1,1,222,67,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
5,6,Gurley,Todd,Todd Gurley,1,1,360,68,RB,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
6,7,Kamara,Alvin,Alvin Kamara,1,1,208,63,RB,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
7,8,Hopkins,DeAndre,DeAndre Hopkins,1,1,155,67,WR,HOU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0
8,9,Fournette,Leonard,Leonard Fournette,1,1,160,67,RB,JAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.0
9,10,Beckham,Odell,Odell Beckham,1,1,262,67,WR,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0
10,11,Hunt,Kareem,Kareem Hunt,1,1,198,65,RB,FA*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0
11,12,Gordon,Melvin,Melvin Gordon,1,1,194,68,RB,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0
12,13,Cook,Dalvin,Dalvin Cook,2,1,219,68,RB,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.5
13,14,Jones,Julio,Julio Jones,2,1,190,69,WR,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0
14,15,Thomas,Michael,Michael Thomas,2,1,161,68,WR,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0
15,16,McCaffrey,Christian,Christian McCaffrey,2,1,156,70,RB,CAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
16,17,Adams,Davante,Davante Adams,2,1,175,69,WR,GBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0
17,18,Allen,Keenan,Keenan Allen,2,1,169,70,WR,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0
18,19,Rodgers,Aaron,Aaron Rodgers,2,1,288,67,QB,GBP,...,2.0,49.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0
19,20,Gronkowski,Rob,Rob Gronkowski,2,1,223,71,TE,NEP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172.0
20,21,Evans,Mike,Mike Evans,2,1,196,71,WR,TBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5
21,22,Mixon,Joe,Joe Mixon,2,1,191,72,RB,CIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0
22,23,Hill,Tyreek,Tyreek Hill,2,1,189,71,WR,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0
23,24,Kelce,Travis,Travis Kelce,2,1,205,72,TE,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0
24,25,Howard,Jordan,Jordan Howard,3,1,198,70,RB,CHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.5
25,26,Diggs,Stefon,Stefon Diggs,3,1,254,71,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0
26,27,Hilton,T.Y.,T.Y. Hilton,3,1,186,74,WR,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
27,28,McCoy,LeSean,LeSean McCoy,3,1,289,73,RB,BUF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.0
28,29,Cooper,Amari,Amari Cooper,3,1,221,75,WR,DAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0
29,30,Watson,Deshaun,Deshaun Watson,3,1,380,65,QB,HOU,...,9.0,62.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0
30,31,Landry,Jarvis,Jarvis Landry,3,1,180,74,WR,CLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0
31,32,Thielen,Adam,Adam Thielen,3,1,331,70,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0
32,33,Ertz,Zach,Zach Ertz,3,1,248,72,TE,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0
33,34,Smith-Schuster,JuJu,JuJu Smith-Schuster,3,1,223,71,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5
34,35,Cooks,Brandin,Brandin Cooks,3,1,173,75,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0
35,36,Wilson,Russell,Russell Wilson,3,1,214,71,QB,SEA,...,7.0,51.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0
36,37,Fitzgerald,Larry,Larry Fitzgerald,4,1,534,75,WR,ARI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0
37,38,Brady,Tom,Tom Brady,4,1,280,70,QB,NEP,...,11.0,21.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0
38,39,Baldwin,Doug,Doug Baldwin,4,1,197,74,WR,SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155.0
39,40,Freeman,Royce,Royce Freeman,4,1,638,95,RB,DEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,204.0
40,41,Drake,Kenyan,Kenyan Drake,4,1,261,74,RB,MIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0
41,42,Robinson,Allen,Allen Robinson,4,1,208,77,WR,CHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.0
42,43,Henry,Derrick,Derrick Henry,4,1,289,72,RB,TEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0
43,44,Michel,Sony,Sony Michel,4,1,634,96,RB,NEP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.0
44,45,Miller,Lamar,Lamar Miller,4,1,247,76,RB,HOU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0
45,46,Newton,Cam,Cam Newton,4,1,384,71,QB,CAR,...,13.0,29.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5
46,47,Graham,Jimmy,Jimmy Graham,4,1,317,74,TE,GBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187.0
47,48,Tate,Golden,Golden Tate,4,1,235,76,WR,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0
48,49,Hogan,Chris,Chris Hogan,5,1,496,78,WR,NEP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,219.0
49,50,Brees,Drew,Drew Brees,5,1,352,73,QB,NOS,...,5.0,17.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,12.0
50,51,Davis,Corey,Corey Davis,5,2,251,74,WR,TEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0
51,52,Jeffery,Alshon,Alshon Jeffery,5,1,345,76,WR,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0
52,53,Engram,Evan,Evan Engram,5,1,376,72,TE,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182.0
53,54,Penny,Rashaad,Rashaad Penny,5,1,663,93,RB,SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,276.5
54,55,Ingram,Mark,Mark Ingram,5,1,276,73,RB,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.5
55,56,Wentz,Carson,Carson Wentz,5,1,383,68,QB,PHI,...,7.0,31.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,55.0
56,57,Williams,Jamaal,Jamaal Williams,5,1,357,75,RB,GBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190.5
57,59,Watkins,Sammy,Sammy Watkins,5,1,274,77,WR,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,203.0
58,61,Lewis,Dion,Dion Lewis,5,1,332,74,RB,TEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.0
59,62,Jones,Ronald,Ronald Jones,5,1,647,83,RB,TBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,438.0

In [6]:
rb = d.loc[d['Position'] == 'RB']
wr = d.loc[d['Position'] == 'WR']

In [8]:
wr['performance_fp_wr'] = wr['FantasyPointsRank'].rank(ascending = True)
rb['performance_fp_rb'] = rb['FantasyPointsRank'].rank(ascending = True)

<ipython-input-8-ea88c15edb18>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wr['performance_fp_wr'] = wr['FantasyPointsRank'].rank(ascending = True)
<ipython-input-8-ea88c15edb18>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rb['performance_fp_rb'] = rb['FantasyPointsRank'].rank(ascending = True)

In [10]:
te = d.loc[d['Position'] == 'TE']
te['performance_fp_te'] = te['FantasyPointsRank'].rank(ascending = True)

<ipython-input-10-c576e4e6ce8f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  te['performance_fp_te'] = te['FantasyPointsRank'].rank(ascending = True)

In [12]:
qb = d.loc[d['Position'] == 'QB']
qb['performance_fp_qb'] = qb['FantasyPointsRank'].rank(ascending = True)

<ipython-input-12-4882867569a5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb['performance_fp_qb'] = qb['FantasyPointsRank'].rank(ascending = True)

In [14]:
k = d.loc[d['Position'] == 'PK']
k['performance_fp_qb'] = k['FantasyPointsRank'].rank(ascending = True)

<ipython-input-14-d0b0a0dfd751>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['performance_fp_qb'] = k['FantasyPointsRank'].rank(ascending = True)

In [15]:
Def = d.loc[d['Position'] == 'Def']
Def['performance_fp_qb'] = Def['FantasyPointsRank'].rank(ascending = True)

<ipython-input-15-0fe04eefa7f5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Def['performance_fp_qb'] = Def['FantasyPointsRank'].rank(ascending = True)

In [17]:
rb_50 = rb.head(50)
after_rb = rb_50[(rb_50['FantasyPointsRank'] <= 70)]
after_rb.head(50)

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_rb
1,2,Elliott,Ezekiel,Ezekiel Elliott,1,1,186,67,RB,DAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0
2,3,Johnson,David,David Johnson,1,1,198,65,RB,ARI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,10.0
3,4,Barkley,Saquon,Saquon Barkley,1,1,451,95,RB,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0
5,6,Gurley,Todd,Todd Gurley,1,1,360,68,RB,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
6,7,Kamara,Alvin,Alvin Kamara,1,1,208,63,RB,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,4.0
10,11,Hunt,Kareem,Kareem Hunt,1,1,198,65,RB,FA*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,11.0
11,12,Gordon,Melvin,Melvin Gordon,1,1,194,68,RB,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,7.0
15,16,McCaffrey,Christian,Christian McCaffrey,2,1,156,70,RB,CAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,3.0
21,22,Mixon,Joe,Joe Mixon,2,1,191,72,RB,CIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,9.0
40,41,Drake,Kenyan,Kenyan Drake,4,1,261,74,RB,MIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,16.0
42,43,Henry,Derrick,Derrick Henry,4,1,289,72,RB,TEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,13.0
62,65,Coleman,Tevin,Tevin Coleman,6,1,274,75,RB,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,18.0
73,82,Cohen,Tarik,Tarik Cohen,7,1,300,73,RB,CHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0,12.0
76,85,Chubb,Nick,Nick Chubb,7,1,642,80,RB,CLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,15.0
90,106,Peterson,Adrian,Adrian Peterson,8,1,827,60,RB,WAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.0,17.0
99,115,Carson,Chris,Chris Carson,9,1,425,72,RB,SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,14.0
130,156,White,James,James White,11,2,406,68,RB,NEP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,8.0

In [19]:
wr_50 = wr.head(50)
after_wr = wr_50[(wr_50['FantasyPointsRank'] <= 70)]
after_wr.head(50)

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_wr
4,5,Brown,Antonio,Antonio Brown,1,1,222,67,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,4.0
7,8,Hopkins,DeAndre,DeAndre Hopkins,1,1,155,67,WR,HOU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,2.0
9,10,Beckham,Odell,Odell Beckham,1,1,262,67,WR,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,16.0
13,14,Jones,Julio,Julio Jones,2,1,190,69,WR,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,5.0
14,15,Thomas,Michael,Michael Thomas,2,1,161,68,WR,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,6.0
16,17,Adams,Davante,Davante Adams,2,1,175,69,WR,GBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,3.0
17,18,Allen,Keenan,Keenan Allen,2,1,169,70,WR,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,12.0
20,21,Evans,Mike,Mike Evans,2,1,196,71,WR,TBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5,8.5
22,23,Hill,Tyreek,Tyreek Hill,2,1,189,71,WR,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,1.0
25,26,Diggs,Stefon,Stefon Diggs,3,1,254,71,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,11.0
26,27,Hilton,T.Y.,T.Y. Hilton,3,1,186,74,WR,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,14.0
28,29,Cooper,Amari,Amari Cooper,3,1,221,75,WR,DAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,17.0
30,31,Landry,Jarvis,Jarvis Landry,3,1,180,74,WR,CLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0,18.0
31,32,Thielen,Adam,Adam Thielen,3,1,331,70,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,7.0
33,34,Smith-Schuster,JuJu,JuJu Smith-Schuster,3,1,223,71,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5,8.5
34,35,Cooks,Brandin,Brandin Cooks,3,1,173,75,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,13.0
72,76,Woods,Robert,Robert Woods,7,2,302,76,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0,10.0
82,95,Ridley,Calvin,Calvin Ridley,7,1,643,79,WR,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.0,19.0

In [20]:
te_50 = te.head(50)
after_te = te_50[(te_50['FantasyPointsRank'] <= 70)]
after_te.head(30)

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_te
23,24,Kelce,Travis,Travis Kelce,2,1,205,72,TE,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,1.0
32,33,Ertz,Zach,Zach Ertz,3,1,248,72,TE,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0,2.0
139,169,Kittle,George,George Kittle,12,1,429,63,TE,SFO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,3.0
183,227,Ebron,Eric,Eric Ebron,16,1,519,46,TE,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,4.0

In [21]:
qb_50 = qb.head(50)
after_qb = qb_50[(qb_50['FantasyPointsRank'] <= 70)]
after_qb.head(30)

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_qb
18,19,Rodgers,Aaron,Aaron Rodgers,2,1,288,67,QB,GBP,...,49.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,6.0
29,30,Watson,Deshaun,Deshaun Watson,3,1,380,65,QB,HOU,...,62.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,4.0
35,36,Wilson,Russell,Russell Wilson,3,1,214,71,QB,SEA,...,51.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,9.0
37,38,Brady,Tom,Tom Brady,4,1,280,70,QB,NEP,...,21.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,14.0
45,46,Newton,Cam,Cam Newton,4,1,384,71,QB,CAR,...,29.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5,12.5
49,50,Brees,Drew,Drew Brees,5,1,352,73,QB,NOS,...,17.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,12.0,8.0
55,56,Wentz,Carson,Carson Wentz,5,1,383,68,QB,PHI,...,31.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,55.0,23.0
64,68,Cousins,Kirk,Kirk Cousins,6,1,334,72,QB,MIN,...,40.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5,12.5
67,71,Luck,Andrew,Andrew Luck,6,1,314,73,QB,IND,...,18.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,5.0
74,83,Stafford,Matthew,Matthew Stafford,7,1,269,72,QB,DET,...,40.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,45.0,20.0
77,88,Rivers,Philip,Philip Rivers,7,1,410,75,QB,LAC,...,32.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,16.0,11.0
79,91,Roethlisberger,Ben,Ben Roethlisberger,7,1,358,73,QB,PIT,...,24.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0
86,100,Ryan,Matt,Matt Ryan,8,1,421,72,QB,ATL,...,42.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
89,105,Goff,Jared,Jared Goff,8,1,358,71,QB,LAR,...,33.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,11.0,7.0
94,110,Mayfield,Baker,Baker Mayfield,8,1,645,48,QB,CLE,...,25.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,33.5,16.5
98,114,Mahomes,Patrick,Patrick Mahomes,9,1,354,71,QB,KCC,...,26.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
103,120,Allen,Josh,Josh Allen,9,1,699,32,QB,BUF,...,28.0,89.0,NaN,NaN,NaN,NaN,NaN,NaN,47.0,21.0
132,160,Prescott,Dak,Dak Prescott,12,1,356,64,QB,DAL,...,56.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,10.0
134,164,Mariota,Marcus,Marcus Mariota,12,1,499,62,QB,TEN,...,42.0,64.0,NaN,NaN,NaN,NaN,NaN,NaN,67.0,24.0
144,174,Carr,Derek,Derek Carr,13,1,379,60,QB,OAK,...,51.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,41.0,18.0
153,185,Winston,Jameis,Jameis Winston,13,1,404,40,QB,TBB,...,27.0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,52.0,22.0
160,197,Trubisky,Mitchell,Mitchell Trubisky,14,1,462,39,QB,CHI,...,24.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,15.0
170,210,Bortles,Blake,Blake Bortles,15,1,503,45,QB,JAC,...,31.0,58.0,NaN,NaN,NaN,NaN,NaN,NaN,70.0,25.0
177,219,Keenum,Case,Case Keenum,15,1,546,35,QB,DEN,...,34.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,43.0,19.0
181,225,Manning,Eli,Eli Manning,16,1,528,42,QB,NYG,...,47.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,33.5,16.5

In [22]:
rb1 = rb[(rb['FantasyPointsRank'] <= 100)]
wr1 = wr[(wr['FantasyPointsRank'] <= 100)]
te1 = te[(te['FantasyPointsRank'] <= 100)]
qb1 = qb[(qb['FantasyPointsRank'] <= 100)]
rb1

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_rb
1,2,Elliott,Ezekiel,Ezekiel Elliott,1,1,186,67,RB,DAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0
2,3,Johnson,David,David Johnson,1,1,198,65,RB,ARI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,10.0
3,4,Barkley,Saquon,Saquon Barkley,1,1,451,95,RB,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0
5,6,Gurley,Todd,Todd Gurley,1,1,360,68,RB,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
6,7,Kamara,Alvin,Alvin Kamara,1,1,208,63,RB,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,4.0
10,11,Hunt,Kareem,Kareem Hunt,1,1,198,65,RB,FA*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,11.0
11,12,Gordon,Melvin,Melvin Gordon,1,1,194,68,RB,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,7.0
15,16,McCaffrey,Christian,Christian McCaffrey,2,1,156,70,RB,CAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,3.0
21,22,Mixon,Joe,Joe Mixon,2,1,191,72,RB,CIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,9.0
24,25,Howard,Jordan,Jordan Howard,3,1,198,70,RB,CHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.5,19.0
40,41,Drake,Kenyan,Kenyan Drake,4,1,261,74,RB,MIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,16.0
42,43,Henry,Derrick,Derrick Henry,4,1,289,72,RB,TEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,13.0
44,45,Miller,Lamar,Lamar Miller,4,1,247,76,RB,HOU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.0,21.0
62,65,Coleman,Tevin,Tevin Coleman,6,1,274,75,RB,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,18.0
73,82,Cohen,Tarik,Tarik Cohen,7,1,300,73,RB,CHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0,12.0
76,85,Chubb,Nick,Nick Chubb,7,1,642,80,RB,CLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,15.0
81,94,Mack,Marlon,Marlon Mack,7,1,351,73,RB,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,20.0
90,106,Peterson,Adrian,Adrian Peterson,8,1,827,60,RB,WAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.0,17.0
99,115,Carson,Chris,Chris Carson,9,1,425,72,RB,SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,14.0
130,156,White,James,James White,11,2,406,68,RB,NEP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,8.0
186,231,Conner,James,James Conner,16,1,601,41,RB,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,6.0
204,260,Yeldon,T.J.,T.J. Yeldon,18,1,501,38,RB,JAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.0,23.0
205,261,Ekeler,Austin,Austin Ekeler,18,2,551,35,RB,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0,22.0

In [23]:
wr1

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_wr
4,5,Brown,Antonio,Antonio Brown,1,1,222,67,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,4.0
7,8,Hopkins,DeAndre,DeAndre Hopkins,1,1,155,67,WR,HOU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,2.0
9,10,Beckham,Odell,Odell Beckham,1,1,262,67,WR,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,16.0
13,14,Jones,Julio,Julio Jones,2,1,190,69,WR,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,5.0
14,15,Thomas,Michael,Michael Thomas,2,1,161,68,WR,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,6.0
16,17,Adams,Davante,Davante Adams,2,1,175,69,WR,GBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,3.0
17,18,Allen,Keenan,Keenan Allen,2,1,169,70,WR,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,12.0
20,21,Evans,Mike,Mike Evans,2,1,196,71,WR,TBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5,8.5
22,23,Hill,Tyreek,Tyreek Hill,2,1,189,71,WR,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,1.0
25,26,Diggs,Stefon,Stefon Diggs,3,1,254,71,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,11.0
26,27,Hilton,T.Y.,T.Y. Hilton,3,1,186,74,WR,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,14.0
28,29,Cooper,Amari,Amari Cooper,3,1,221,75,WR,DAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,17.0
30,31,Landry,Jarvis,Jarvis Landry,3,1,180,74,WR,CLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0,18.0
31,32,Thielen,Adam,Adam Thielen,3,1,331,70,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,7.0
33,34,Smith-Schuster,JuJu,JuJu Smith-Schuster,3,1,223,71,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5,8.5
34,35,Cooks,Brandin,Brandin Cooks,3,1,173,75,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,13.0
36,37,Fitzgerald,Larry,Larry Fitzgerald,4,1,534,75,WR,ARI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,25.0
47,48,Tate,Golden,Golden Tate,4,1,235,76,WR,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,30.0
50,51,Davis,Corey,Corey Davis,5,2,251,74,WR,TEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,26.0
51,52,Jeffery,Alshon,Alshon Jeffery,5,1,345,76,WR,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,24.0
60,63,Edelman,Julian,Julian Edelman,6,1,299,75,WR,NEP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0,21.0
72,76,Woods,Robert,Robert Woods,7,2,302,76,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0,10.0
82,95,Ridley,Calvin,Calvin Ridley,7,1,643,79,WR,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.0,19.0
117,138,Shepard,Sterling,Sterling Shepard,10,1,349,67,WR,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,28.0
138,168,Williams,Mike,Mike Williams,12,4,436,57,WR,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.0,22.0
154,187,Golladay,Kenny,Kenny Golladay,13,4,474,53,WR,DET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.0,20.0
162,200,Lockett,Tyler,Tyler Lockett,14,2,455,51,WR,SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.0,15.0
173,213,Sanu,Mohamed,Mohamed Sanu,15,2,568,56,WR,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.0,29.0
180,222,Godwin,Chris,Chris Godwin,16,1,472,37,WR,TBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0,23.0
288,351,Humphries,Adam,Adam Humphries,25,9,768,9,WR,TBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0,27.0

In [24]:
te1

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_te
23,24,Kelce,Travis,Travis Kelce,2,1,205,72,TE,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,1.0
32,33,Ertz,Zach,Zach Ertz,3,1,248,72,TE,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0,2.0
139,169,Kittle,George,George Kittle,12,1,429,63,TE,SFO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,3.0
183,227,Ebron,Eric,Eric Ebron,16,1,519,46,TE,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,4.0
188,236,Cook,Jared,Jared Cook,16,3,557,48,TE,OAK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0,5.0

In [25]:
qb1

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_qb
18,19,Rodgers,Aaron,Aaron Rodgers,2,1,288,67,QB,GBP,...,49.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,6.0
29,30,Watson,Deshaun,Deshaun Watson,3,1,380,65,QB,HOU,...,62.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,4.0
35,36,Wilson,Russell,Russell Wilson,3,1,214,71,QB,SEA,...,51.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,9.0
37,38,Brady,Tom,Tom Brady,4,1,280,70,QB,NEP,...,21.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,14.0
45,46,Newton,Cam,Cam Newton,4,1,384,71,QB,CAR,...,29.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5,12.5
49,50,Brees,Drew,Drew Brees,5,1,352,73,QB,NOS,...,17.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,12.0,8.0
55,56,Wentz,Carson,Carson Wentz,5,1,383,68,QB,PHI,...,31.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,55.0,23.0
64,68,Cousins,Kirk,Kirk Cousins,6,1,334,72,QB,MIN,...,40.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5,12.5
67,71,Luck,Andrew,Andrew Luck,6,1,314,73,QB,IND,...,18.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,5.0
74,83,Stafford,Matthew,Matthew Stafford,7,1,269,72,QB,DET,...,40.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,45.0,20.0
77,88,Rivers,Philip,Philip Rivers,7,1,410,75,QB,LAC,...,32.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,16.0,11.0
79,91,Roethlisberger,Ben,Ben Roethlisberger,7,1,358,73,QB,PIT,...,24.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0
84,97,Jackson,Lamar,Lamar Jackson,8,1,1040,38,QB,BAL,...,16.0,147.0,NaN,NaN,NaN,NaN,NaN,NaN,84.0,28.0
86,100,Ryan,Matt,Matt Ryan,8,1,421,72,QB,ATL,...,42.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
89,105,Goff,Jared,Jared Goff,8,1,358,71,QB,LAR,...,33.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,11.0,7.0
94,110,Mayfield,Baker,Baker Mayfield,8,1,645,48,QB,CLE,...,25.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,33.5,16.5
98,114,Mahomes,Patrick,Patrick Mahomes,9,1,354,71,QB,KCC,...,26.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
100,116,Darnold,Sam,Sam Darnold,9,1,647,42,QB,NYJ,...,30.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,76.0,26.0
103,120,Allen,Josh,Josh Allen,9,1,699,32,QB,BUF,...,28.0,89.0,NaN,NaN,NaN,NaN,NaN,NaN,47.0,21.0
132,160,Prescott,Dak,Dak Prescott,12,1,356,64,QB,DAL,...,56.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,10.0
134,164,Mariota,Marcus,Marcus Mariota,12,1,499,62,QB,TEN,...,42.0,64.0,NaN,NaN,NaN,NaN,NaN,NaN,67.0,24.0
144,174,Carr,Derek,Derek Carr,13,1,379,60,QB,OAK,...,51.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,41.0,18.0
153,185,Winston,Jameis,Jameis Winston,13,1,404,40,QB,TBB,...,27.0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,52.0,22.0
160,197,Trubisky,Mitchell,Mitchell Trubisky,14,1,462,39,QB,CHI,...,24.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,15.0
170,210,Bortles,Blake,Blake Bortles,15,1,503,45,QB,JAC,...,31.0,58.0,NaN,NaN,NaN,NaN,NaN,NaN,70.0,25.0
177,219,Keenum,Case,Case Keenum,15,1,546,35,QB,DEN,...,34.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,43.0,19.0
181,225,Manning,Eli,Eli Manning,16,1,528,42,QB,NYG,...,47.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,33.5,16.5
272,336,Fitzpatrick,Ryan,Ryan Fitzpatrick,23,1,977,6,QB,TBB,...,14.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,77.0,27.0

In [26]:
rb2 = rb[(rb['FantasyPointsRank'] <= 50)]
wr2 = wr[(wr['FantasyPointsRank'] <= 50)]
te2 = te[(te['FantasyPointsRank'] <= 50)]
qb2 = qb[(qb['FantasyPointsRank'] <= 50)]
rb2

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_rb
1,2,Elliott,Ezekiel,Ezekiel Elliott,1,1,186,67,RB,DAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0
2,3,Johnson,David,David Johnson,1,1,198,65,RB,ARI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,10.0
3,4,Barkley,Saquon,Saquon Barkley,1,1,451,95,RB,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0
5,6,Gurley,Todd,Todd Gurley,1,1,360,68,RB,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
6,7,Kamara,Alvin,Alvin Kamara,1,1,208,63,RB,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,4.0
10,11,Hunt,Kareem,Kareem Hunt,1,1,198,65,RB,FA*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,11.0
11,12,Gordon,Melvin,Melvin Gordon,1,1,194,68,RB,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,7.0
15,16,McCaffrey,Christian,Christian McCaffrey,2,1,156,70,RB,CAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,3.0
21,22,Mixon,Joe,Joe Mixon,2,1,191,72,RB,CIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,9.0
130,156,White,James,James White,11,2,406,68,RB,NEP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,8.0
186,231,Conner,James,James Conner,16,1,601,41,RB,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,6.0

In [27]:
wr2

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_wr
4,5,Brown,Antonio,Antonio Brown,1,1,222,67,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,4.0
7,8,Hopkins,DeAndre,DeAndre Hopkins,1,1,155,67,WR,HOU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,2.0
13,14,Jones,Julio,Julio Jones,2,1,190,69,WR,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,5.0
14,15,Thomas,Michael,Michael Thomas,2,1,161,68,WR,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,6.0
16,17,Adams,Davante,Davante Adams,2,1,175,69,WR,GBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,3.0
17,18,Allen,Keenan,Keenan Allen,2,1,169,70,WR,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,12.0
20,21,Evans,Mike,Mike Evans,2,1,196,71,WR,TBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5,8.5
22,23,Hill,Tyreek,Tyreek Hill,2,1,189,71,WR,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,1.0
25,26,Diggs,Stefon,Stefon Diggs,3,1,254,71,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,11.0
26,27,Hilton,T.Y.,T.Y. Hilton,3,1,186,74,WR,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,14.0
31,32,Thielen,Adam,Adam Thielen,3,1,331,70,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,7.0
33,34,Smith-Schuster,JuJu,JuJu Smith-Schuster,3,1,223,71,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5,8.5
34,35,Cooks,Brandin,Brandin Cooks,3,1,173,75,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,13.0
72,76,Woods,Robert,Robert Woods,7,2,302,76,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0,10.0

In [28]:
te2

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_te
23,24,Kelce,Travis,Travis Kelce,2,1,205,72,TE,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,1.0
32,33,Ertz,Zach,Zach Ertz,3,1,248,72,TE,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0,2.0
139,169,Kittle,George,George Kittle,12,1,429,63,TE,SFO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,3.0

In [29]:
qb2

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_qb
18,19,Rodgers,Aaron,Aaron Rodgers,2,1,288,67,QB,GBP,...,49.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,6.0
29,30,Watson,Deshaun,Deshaun Watson,3,1,380,65,QB,HOU,...,62.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,4.0
35,36,Wilson,Russell,Russell Wilson,3,1,214,71,QB,SEA,...,51.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,9.0
37,38,Brady,Tom,Tom Brady,4,1,280,70,QB,NEP,...,21.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,14.0
45,46,Newton,Cam,Cam Newton,4,1,384,71,QB,CAR,...,29.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5,12.5
49,50,Brees,Drew,Drew Brees,5,1,352,73,QB,NOS,...,17.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,12.0,8.0
64,68,Cousins,Kirk,Kirk Cousins,6,1,334,72,QB,MIN,...,40.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5,12.5
67,71,Luck,Andrew,Andrew Luck,6,1,314,73,QB,IND,...,18.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,5.0
74,83,Stafford,Matthew,Matthew Stafford,7,1,269,72,QB,DET,...,40.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,45.0,20.0
77,88,Rivers,Philip,Philip Rivers,7,1,410,75,QB,LAC,...,32.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,16.0,11.0
79,91,Roethlisberger,Ben,Ben Roethlisberger,7,1,358,73,QB,PIT,...,24.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0
86,100,Ryan,Matt,Matt Ryan,8,1,421,72,QB,ATL,...,42.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
89,105,Goff,Jared,Jared Goff,8,1,358,71,QB,LAR,...,33.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,11.0,7.0
94,110,Mayfield,Baker,Baker Mayfield,8,1,645,48,QB,CLE,...,25.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,33.5,16.5
98,114,Mahomes,Patrick,Patrick Mahomes,9,1,354,71,QB,KCC,...,26.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
103,120,Allen,Josh,Josh Allen,9,1,699,32,QB,BUF,...,28.0,89.0,NaN,NaN,NaN,NaN,NaN,NaN,47.0,21.0
132,160,Prescott,Dak,Dak Prescott,12,1,356,64,QB,DAL,...,56.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,10.0
144,174,Carr,Derek,Derek Carr,13,1,379,60,QB,OAK,...,51.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,41.0,18.0
160,197,Trubisky,Mitchell,Mitchell Trubisky,14,1,462,39,QB,CHI,...,24.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,15.0
177,219,Keenum,Case,Case Keenum,15,1,546,35,QB,DEN,...,34.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,43.0,19.0
181,225,Manning,Eli,Eli Manning,16,1,528,42,QB,NYG,...,47.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,33.5,16.5

In [30]:
rb3 = rb[(rb['FantasyPointsRank'] <= 25)]
wr3 = wr[(wr['FantasyPointsRank'] <= 25)]
te3 = te[(te['FantasyPointsRank'] <= 25)]
qb3 = qb[(qb['FantasyPointsRank'] <= 25)]
rb3

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_rb
1,2,Elliott,Ezekiel,Ezekiel Elliott,1,1,186,67,RB,DAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0
3,4,Barkley,Saquon,Saquon Barkley,1,1,451,95,RB,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0
5,6,Gurley,Todd,Todd Gurley,1,1,360,68,RB,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0
6,7,Kamara,Alvin,Alvin Kamara,1,1,208,63,RB,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,4.0
15,16,McCaffrey,Christian,Christian McCaffrey,2,1,156,70,RB,CAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,3.0

In [31]:
wr3

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_wr
4,5,Brown,Antonio,Antonio Brown,1,1,222,67,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,4.0
7,8,Hopkins,DeAndre,DeAndre Hopkins,1,1,155,67,WR,HOU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,2.0
13,14,Jones,Julio,Julio Jones,2,1,190,69,WR,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,5.0
16,17,Adams,Davante,Davante Adams,2,1,175,69,WR,GBP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,3.0
22,23,Hill,Tyreek,Tyreek Hill,2,1,189,71,WR,KCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,1.0

In [34]:
wr3['FantasyPointsRank'].sum()

107.0

In [32]:
te3

Empty DataFrame
Columns: [Rank_x, Player_x, Unnamed: 2, Player_Name, Round, Min Pick, Max Pick, % Selected, Position, Team, PositionRank, Rank_y, Player_y, ATT, YDS, Y/A, LG, 20+, TD, REC, TGT, YDS.1, Y/R, TD.1, FL, G, FPTS, FPTS/G, OWN, FG, FGA, PCT, 1-19, 20-29, 30-39, 40-49, 50+, XPT, XPA, CMP, INT, SACKS, ATT.1, SACK, FR, FF, DEF TD, SFTY, SPC TD, FantasyPointsRank, performance_fp_te]
Index: []

[0 rows x 51 columns]

In [33]:
qb3

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_qb
18,19,Rodgers,Aaron,Aaron Rodgers,2,1,288,67,QB,GBP,...,49.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,6.0
29,30,Watson,Deshaun,Deshaun Watson,3,1,380,65,QB,HOU,...,62.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,4.0
35,36,Wilson,Russell,Russell Wilson,3,1,214,71,QB,SEA,...,51.0,67.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,9.0
37,38,Brady,Tom,Tom Brady,4,1,280,70,QB,NEP,...,21.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,14.0
45,46,Newton,Cam,Cam Newton,4,1,384,71,QB,CAR,...,29.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5,12.5
49,50,Brees,Drew,Drew Brees,5,1,352,73,QB,NOS,...,17.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,12.0,8.0
64,68,Cousins,Kirk,Kirk Cousins,6,1,334,72,QB,MIN,...,40.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,18.5,12.5
67,71,Luck,Andrew,Andrew Luck,6,1,314,73,QB,IND,...,18.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,5.0
77,88,Rivers,Philip,Philip Rivers,7,1,410,75,QB,LAC,...,32.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,16.0,11.0
79,91,Roethlisberger,Ben,Ben Roethlisberger,7,1,358,73,QB,PIT,...,24.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0
86,100,Ryan,Matt,Matt Ryan,8,1,421,72,QB,ATL,...,42.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
89,105,Goff,Jared,Jared Goff,8,1,358,71,QB,LAR,...,33.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,11.0,7.0
98,114,Mahomes,Patrick,Patrick Mahomes,9,1,354,71,QB,KCC,...,26.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
132,160,Prescott,Dak,Dak Prescott,12,1,356,64,QB,DAL,...,56.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,10.0
160,197,Trubisky,Mitchell,Mitchell Trubisky,14,1,462,39,QB,CHI,...,24.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,15.0

In [35]:
rb_25_50 = rb2[(rb2['FantasyPointsRank'] >= 25)]
wr_25_50 = wr2[(wr2['FantasyPointsRank'] >= 25)]
te_25_50 = te2[(te2['FantasyPointsRank'] >= 25)]
qb_25_50 = qb2[(qb2['FantasyPointsRank'] >= 25)]
rb_25_50

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_rb
2,3,Johnson,David,David Johnson,1,1,198,65,RB,ARI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,10.0
10,11,Hunt,Kareem,Kareem Hunt,1,1,198,65,RB,FA*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,11.0
11,12,Gordon,Melvin,Melvin Gordon,1,1,194,68,RB,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,7.0
21,22,Mixon,Joe,Joe Mixon,2,1,191,72,RB,CIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,9.0
130,156,White,James,James White,11,2,406,68,RB,NEP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,8.0
186,231,Conner,James,James Conner,16,1,601,41,RB,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,6.0

In [37]:
rb_25_50['FantasyPointsRank'].sum()

208.0

In [36]:
wr_25_50

,Rank_x,Player_x,Unnamed: 2,Player_Name,Round,Min Pick,Max Pick,% Selected,Position,Team,...,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank,performance_fp_wr
14,15,Thomas,Michael,Michael Thomas,2,1,161,68,WR,NOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,6.0
17,18,Allen,Keenan,Keenan Allen,2,1,169,70,WR,LAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,12.0
20,21,Evans,Mike,Mike Evans,2,1,196,71,WR,TBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5,8.5
25,26,Diggs,Stefon,Stefon Diggs,3,1,254,71,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,11.0
26,27,Hilton,T.Y.,T.Y. Hilton,3,1,186,74,WR,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,14.0
31,32,Thielen,Adam,Adam Thielen,3,1,331,70,WR,MIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,7.0
33,34,Smith-Schuster,JuJu,JuJu Smith-Schuster,3,1,223,71,WR,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.5,8.5
34,35,Cooks,Brandin,Brandin Cooks,3,1,173,75,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,13.0
72,76,Woods,Robert,Robert Woods,7,2,302,76,WR,LAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0,10.0

In [38]:
wr_25_50['FantasyPointsRank'].sum()

340.0