In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from matplotlib import rcParams

%matplotlib inline

In [2]:
adp = pd.read_csv('Data/Ranked_adp_for_merge/adp_ranked_2017 - adp_ranked_2017.csv')

In [3]:
fp = pd.read_csv('Data/clean_fp_data_merge/fp_data_cleaned_17 - fp_data_uncleaned_17 - fp_data_uncleaned_17.csv')

In [4]:
adp.shape

(295, 10)

In [5]:
fp['Player'] = fp['Player'].str.strip()

fp.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
0,1,Todd Gurley,279.0,"1,305",4.7,57.0,8.0,13.0,64.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,Russell Wilson,553.0,"3,983",7.2,NaN,NaN,34.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,339.0,11.0,43.0,95.0,2.0
2,2,Cam Newton,492.0,"3,302",6.7,NaN,NaN,22.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,291.0,16.0,35.0,139.0,3.0
3,2,Le'Veon Bell,321.0,"1,291",4.0,27.0,3.0,9.0,85.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
4,3,Tom Brady,581.0,"4,577",7.9,NaN,NaN,32.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,385.0,8.0,35.0,25.0,5.0

In [9]:
rwd = pd.merge(adp, fp, 
                 left_on = 'Player_Name', right_on = 'Player',
                 how = 'left')
rwd.shape

(296, 43)

In [10]:
rwd.tail(50)
#defense's are no longer in the data so we have an extra 32 missing data links

,Rank_x,Player_x,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
246,290,Booker,Devontae,Devontae Booker,9,728,26,RB,DEN,66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210.0
247,291,Raiders,Oakland,Oakland Raiders,9,571,41,Def,OAK,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,292,Chargers,Los Angeles,Los Angeles Chargers,12,603,39,Def,LAC,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,293,Smith,Torrey,Torrey Smith,1,1669,35,WR,PHI,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,219.5
250,294,Seferian-Jenkins,Austin,Austin Seferian-Jenkins,8,1159,28,TE,NYJ,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,208.5
251,295,Richardson,Paul,Paul Richardson,2,1385,30,WR,SEA,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.0
252,296,Bills,Buffalo,Buffalo Bills,6,757,40,Def,BUF,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,297,Buccaneers,Tampa Bay,Tampa Bay Buccaneers,3,586,39,Def,TBB,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,298,Pitta,Dennis,Dennis Pitta,33,821,5,TE,FA,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,299,Richard,Jalen,Jalen Richard,6,715,27,RB,OAK,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221.0
256,300,Higbee,Tyler,Tyler Higbee,5,1153,14,TE,LAR,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282.0
257,301,Titans,Tennessee,Tennessee Titans,14,741,32,Def,TEN,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,302,Packers,Green Bay,Green Bay Packers,11,766,37,Def,GBP,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,303,Morris,Alfred,Alfred Morris,3,1183,16,RB,DAL,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227.0
260,304,Bengals,Cincinnati,Cincinnati Bengals,5,612,37,Def,CIN,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,305,Goodwin,Marquise,Marquise Goodwin,4,1074,16,WR,SFO,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.0
262,306,Boldin,Anquan,Anquan Boldin,2,835,11,WR,FA,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,307,Dorsett,Phillip,Phillip Dorsett,5,712,10,WR,NEP,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356.0
264,308,Lynch,Paxton,Paxton Lynch,4,882,8,QB,DEN,35,...,NaN,NaN,NaN,NaN,NaN,30.0,3.0,9.0,5.0,404.0
265,309,Oliver,Branden,Branden Oliver,5,1472,13,RB,LAC,69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,417.5
266,310,Boyd,Tyler,Tyler Boyd,10,623,16,WR,CIN,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,292.0
267,311,Rogers,Eli,Eli Rogers,5,1258,12,WR,PIT,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.5
268,312,Cowboys,Dallas,Dallas Cowboys,4,499,26,Def,DAL,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,313,Ivory,Chris,Chris Ivory,8,1087,10,RB,JAC,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215.0
270,314,Drake,Kenyan,Kenyan Drake,1,839,10,RB,MIA,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.5
271,315,Dolphins,Miami,Miami Dolphins,11,761,31,Def,MIA,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,316,Benjamin,Travis,Travis Benjamin,12,655,20,WR,LAC,93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.0
273,317,LaFell,Brandon,Brandon LaFell,11,1075,17,WR,CIN,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166.0
274,318,Watson,Ben,Ben Watson,2,1764,13,TE,BAL,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,319,Aiken,Kamar,Kamar Aiken,5,825,13,WR,IND,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,376.0
276,320,Brown,Jaron,Jaron Brown,7,1038,7,WR,ARI,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.0
277,321,Browns,Cleveland,Cleveland Browns,2,759,11,Def,CLE,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,322,49ers,San Francisco,San Francisco 49ers,5,593,9,Def,SFO,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,323,Bears,Chicago,Chicago Bears,8,658,11,Def,CHI,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,324,Allen,Javorius,Javorius Allen,3,896,5,RB,BAL,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0
281,325,Miller,Braxton,Braxton Miller,3,1305,9,WR,HOU,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.5
282,326,Williams,Terrance,Terrance Williams,1,723,14,WR,DAL,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0
283,327,Hightower,Tim,Tim Hightower,5,1403,10,RB,FA,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,328,Colts,Indianapolis,Indianapolis Colts,34,760,7,Def,IND,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,329,Zenner,Zach,Zach Zenner,2,1815,8,RB,DET,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,467.5
286,330,Redskins,Washington,Washington Redskins,20,770,11,Def,WAS,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,331,Lions,Detroit,Detroit Lions,4,765,9,Def,DET,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,332,Davis,Vernon,Vernon Davis,14,719,13,TE,WAS,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.0
289,333,Floyd,Michael,Michael Floyd,12,764,6,WR,MIN,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,426.0
290,334,Mathews,Ryan,Ryan Mathews,14,823,7,RB,FA,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,335,Barnidge,Gary,Gary Barnidge,21,967,5,TE,FA*,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,336,Langford,Jeremy,Jeremy Langford,16,1112,6,RB,NYJ,76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,337,Patterson,Cordarrelle,Cordarrelle Patterson,15,1308,6,WR,OAK,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224.0
294,337,Patterson,Cordarrelle,Cordarrelle Patterson,15,1308,6,WR,OAK,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,939.0
295,338,Gresham,Jermaine,Jermaine Gresham,13,923,6,TE,ARI,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249.0

In [8]:
rwd.to_csv('merged_data_17.csv', index = False)

In [11]:
rounds_4 = rwd.head(48)
rounds_4['Position'].value_counts()

WR    23
RB    18
QB     4
TE     3
Name: Position, dtype: int64

In [12]:
df = rwd.iloc[0:24]
df['Position'].value_counts()

WR    12
RB    11
TE     1
Name: Position, dtype: int64

In [13]:
first = rwd.iloc[0:12]
first['Position'].value_counts()

RB    6
WR    6
Name: Position, dtype: int64

In [14]:
second = rwd.iloc[12:24]
second['Position'].value_counts()

WR    6
RB    5
TE    1
Name: Position, dtype: int64

In [15]:
third = rwd.iloc[24:36]
third['Position'].value_counts()

RB    5
WR    4
QB    2
TE    1
Name: Position, dtype: int64

In [16]:
fourth = rwd.iloc[36:48]
fourth['Position'].value_counts()

WR    7
QB    2
RB    2
TE    1
Name: Position, dtype: int64