In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from matplotlib import rcParams

%matplotlib inline

In [2]:
adp = pd.read_csv('Data/Ranked_adp_for_merge/adp_ranked_2016 - adp_ranked_2016.csv')

In [3]:
fp = pd.read_csv('Data/clean_fp_data_merge/fp_data_cleaned_16 - fp_data_uncleaned_16 - fp_data_uncleaned_16.csv')

In [4]:
adp.shape

(343, 10)

In [10]:
fp['Player'] = fp['Player'].str.strip()

fp.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
0,1,Aaron Rodgers,610.0,"4,428",7.3,NaN,NaN,40.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,401.0,7.0,35.0,67.0,1.0
1,1,David Johnson,293.0,"1,239",4.2,58.0,6.0,16.0,80.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,2,Matt Ryan,534.0,"4,944",9.3,NaN,NaN,38.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,373.0,7.0,37.0,35.0,3.0
3,3,Drew Brees,673.0,"5,208",7.7,NaN,NaN,37.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,471.0,15.0,27.0,23.0,4.0
4,2,Ezekiel Elliott,322.0,"1,631",5.1,60.0,14.0,15.0,32.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [8]:
rwd = pd.merge(adp, fp, 
                 left_on = 'Player_Name', right_on = 'Player',
                 how = 'left')
rwd.shape

(345, 43)

In [9]:
rwd.tail(50)
#defense's are no longer in the data so we have an extra 32 missing data links

,Rank_x,Player_x,Unnamed: 2,Player_Name,Min Pick,Max Pick,% Selected,Position,Team,PositionRank,...,30-39,40-49,50+,XPT,XPA,CMP,INT,SACKS,ATT.1,FantasyPointsRank
295,364,Hightower,Tim,Tim Hightower,6,732,30,RB,NOS,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,156.0
296,365,Gabbert,Blaine,Blaine Gabbert,5,967,16,QB,SFO,39,...,NaN,NaN,NaN,NaN,NaN,91.0,6.0,11.0,40.0,231.0
297,366,Lambo,Josh,Josh Lambo,3,764,6,PK,SDC,24,...,13.0,6.0,0.0,42.0,46.0,NaN,NaN,NaN,NaN,137.5
298,367,Artis-Payne,Cameron,Cameron Artis-Payne,8,699,24,RB,CAR,84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,348.5
299,368,Brate,Cameron,Cameron Brate,2,735,17,TE,TBB,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0
300,369,Amendola,Danny,Danny Amendola,2,608,21,WR,NEP,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.0
301,370,Bush,Reggie,Reggie Bush,1,987,9,RB,BUF,85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.0
302,371,Gillislee,Mike,Mike Gillislee,3,815,9,RB,BUF,86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,144.0
303,372,Strong,Jaelen,Jaelen Strong,12,636,20,WR,HOU,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,382.5
304,373,Hopkins,Dustin,Dustin Hopkins,15,705,5,PK,WAS,25,...,12.0,7.0,3.0,36.0,39.0,NaN,NaN,NaN,NaN,97.0
305,374,Crowder,Jamison,Jamison Crowder,9,597,22,WR,WAS,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0
306,375,Randle,Rueben,Rueben Randle,6,561,16,WR,CHI,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,376,Smelter,DeAndre,DeAndre Smelter,1,692,6,WR,SFO,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,513.5
308,377,Conley,Chris,Chris Conley,2,628,16,WR,KCC,103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,228.0
309,378,Abbrederis,Jared,Jared Abbrederis,1,1023,7,WR,DET,104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,543.0
310,379,Redskins,Washington,Washington Redskins,9,493,32,Def,WAS,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,380,Cowboys,Dallas,Dallas Cowboys,3,532,22,Def,DAL,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,381,Dolphins,Miami,Miami Dolphins,13,534,31,Def,MIA,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,382,Falcons,Atlanta,Atlanta Falcons,15,482,14,Def,ATL,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,383,LaFell,Brandon,Brandon LaFell,7,597,25,WR,CIN,105,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.5
315,384,Blue,Alfred,Alfred Blue,13,835,7,RB,HOU,87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.0
316,385,Hillman,Ronnie,Ronnie Hillman,2,885,12,RB,SDC,88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,358.0
317,386,Bell,Kenny,Kenny Bell,22,602,5,WR,FA,106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,387,Britt,Kenny,Kenny Britt,5,580,19,WR,RAM,107,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.0
319,388,Ravens,Baltimore,Baltimore Ravens,9,521,32,Def,BAL,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,389,Cunningham,Benny,Benny Cunningham,14,838,9,RB,RAM,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,352.0
321,390,Williams,Maxx,Maxx Williams,4,599,8,TE,BAL,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,985.5
322,391,Kaepernick,Colin,Colin Kaepernick,4,1098,10,QB,SFO,40,...,NaN,NaN,NaN,NaN,NaN,196.0,4.0,36.0,69.0,46.0
323,392,Nelson,J.J.,J.J. Nelson,6,575,11,WR,ARI,108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.0
324,393,Carey,Ka'Deem,Ka'Deem Carey,16,890,7,RB,CHI,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,379.0
325,394,Turbin,Robert,Robert Turbin,7,806,6,RB,IND,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186.0
326,395,Johnson,Stevie,Stevie Johnson,6,744,11,WR,SDC,109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327,396,Colts,Indianapolis,Indianapolis Colts,26,535,27,Def,IND,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,397,49ers,San Francisco,San Francisco 49ers,4,529,14,Def,SFO,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,398,Lions,Detroit,Detroit Lions,25,474,24,Def,DET,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,399,Hardy,Justin,Justin Hardy,8,792,7,WR,ATL,110,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,265.0
331,400,Bears,Chicago,Chicago Bears,8,600,22,Def,CHI,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,401,Ellington,Andre,Andre Ellington,3,681,12,RB,ARI,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370.5
333,402,Buccaneers,Tampa Bay,Tampa Bay Buccaneers,12,505,26,Def,TBB,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,403,Amaro,Jace,Jace Amaro,5,806,10,TE,TEN,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,468.0
335,404,Johnson,Charles,Charles Johnson,4,837,7,WR,MIN,111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,318.0
336,405,Roberts,Seth,Seth Roberts,7,752,9,WR,OAK,112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192.0
337,406,Lee,Marqise,Marqise Lee,9,638,5,WR,JAC,113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.0
338,407,Browns,Cleveland,Cleveland Browns,2,489,7,Def,CLE,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,408,Chargers,San Diego,San Diego Chargers,20,494,10,Def,SDC,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,409,Titans,Tennessee,Tennessee Titans,36,628,12,Def,TEN,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,410,Heyward-Bey,Darrius,Darrius Heyward-Bey,13,799,5,WR,PIT,114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.0
342,411,Donnell,Larry,Larry Donnell,5,727,5,TE,NYG,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,377.5
343,412,Kendricks,Lance,Lance Kendricks,13,724,6,TE,RAM,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,203.0
344,413,Gillmore,Crockett,Crockett Gillmore,26,956,5,TE,BAL,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,393.5

In [11]:
rounds_4 = rwd.head(48)
rounds_4['Position'].value_counts()

WR    25
RB    17
QB     4
TE     2
Name: Position, dtype: int64

In [12]:
df = rwd.iloc[0:24]
df['Position'].value_counts()

WR    14
RB    10
Name: Position, dtype: int64

In [13]:
first = rwd.iloc[0:12]
first['Position'].value_counts()

RB    6
WR    6
Name: Position, dtype: int64

In [14]:
second = rwd.iloc[12:24]
second['Position'].value_counts()

WR    8
RB    4
Name: Position, dtype: int64

In [15]:
third = rwd.iloc[24:36]
third['Position'].value_counts()

WR    6
RB    3
QB    2
TE    1
Name: Position, dtype: int64

In [16]:
fourth = rwd.iloc[36:48]
fourth['Position'].value_counts()

WR    5
RB    4
QB    2
TE    1
Name: Position, dtype: int64