In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.request import urlopen as uReq


import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from matplotlib import rcParams

%matplotlib inline

In [3]:
adp_2017 = pd.read_csv('adp_2017.csv')

In [4]:
wr_adp_17 = adp_2017.loc[adp_2017['Position'] == 'WR']
te_adp_17 = adp_2017.loc[adp_2017['Position'] == 'TE']
qb_adp_17 = adp_2017.loc[adp_2017['Position'] == 'QB']
pk_adp_17 = adp_2017.loc[adp_2017['Position'] == 'PK']
rb_adp_17 = adp_2017.loc[adp_2017['Position'] == 'RB']
def_adp_17 = adp_2017.loc[adp_2017['Position'] == 'Def']

In [5]:
rb_adp_17['PositionRank'] = rb_adp_17['Rank'].rank(ascending = True)
rb_adp_17.sort_values(by = 'PositionRank')
wr_adp_17['PositionRank'] = wr_adp_17['Rank'].rank(ascending = True)
wr_adp_17.sort_values(by = 'PositionRank')
te_adp_17['PositionRank'] = te_adp_17['Rank'].rank(ascending = True)
te_adp_17.sort_values(by = 'PositionRank')
qb_adp_17['PositionRank'] = qb_adp_17['Rank'].rank(ascending = True)
qb_adp_17.sort_values(by = 'PositionRank')
def_adp_17['PositionRank'] = def_adp_17['Rank'].rank(ascending = True)
def_adp_17.sort_values(by = 'PositionRank')
pk_adp_17['PositionRank'] = pk_adp_17['Rank'].rank(ascending = True)
pk_adp_17.sort_values(by = 'PositionRank')

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

,Rank,Player,Avg Pick,Min Pick,Max Pick,% Selected,Position,Team,PositionRank
93,94,"Butker, Harrison",93.29,4,1002,5,PK,KCC,1.0
115,116,"Gostkowski, Stephen",106.42,1,882,50,PK,NEP,2.0
118,119,"Elliott, Jake",108.09,2,1036,5,PK,PHI,3.0
130,131,"Tucker, Justin",113.33,1,1319,45,PK,BAL,4.0
155,156,"Bryant, Matt",123.48,1,643,50,PK,ATL,5.0
187,188,"Forbath, Kai",133.75,3,1028,9,PK,MIN,6.0
190,191,"Bailey, Dan",134.56,3,634,45,PK,DAL,7.0
205,206,"Crosby, Mason",143.02,6,704,45,PK,GBP,8.0
215,216,"Lambo, Josh",146.56,1,1271,8,PK,JAC,9.0
216,217,"Lutz, Wil",148.58,1,1237,43,PK,NOS,10.0
221,222,"Boswell, Chris",150.30,4,744,29,PK,PIT,11.0
230,231,"Vinatieri, Adam",154.68,6,917,41,PK,IND,12.0
240,241,"Prater, Matt",159.90,2,649,38,PK,DET,13.0
247,248,"Walsh, Blair",164.23,6,1270,25,PK,SEA,14.0
248,249,"McManus, Brandon",164.87,3,880,29,PK,DEN,15.0
249,250,"Gano, Graham",164.99,6,807,20,PK,CAR,16.0
252,253,"Succop, Ryan",165.36,6,1019,8,PK,TEN,17.0
257,258,"Hauschka, Steven",169.06,11,713,14,PK,BUF,18.0
264,265,"Hopkins, Dustin",175.58,8,916,23,PK,WAS,19.0
278,279,"Dawson, Phil",185.35,11,994,11,PK,ARI,20.0

In [7]:
adp_17_ranked = pd.concat([wr_adp_17, rb_adp_17, qb_adp_17, pk_adp_17, te_adp_17, def_adp_17])
adp_17_ranked = adp_17_ranked.sort_values(by = 'Rank')

In [8]:
rb_adp_17.to_csv('adp_rb_2017.csv', index = False)
wr_adp_17.to_csv('adp_wr_2017.csv', index = False)
te_adp_17.to_csv('adp_te_2017.csv', index = False)
qb_adp_17.to_csv('adp_qb_2017.csv', index = False)
def_adp_17.to_csv('adp_def_2017.csv', index = False)
pk_adp_17.to_csv('adp_pk_2017.csv', index = False)

adp_17_ranked.to_csv('adp_ranked_2017.csv', index = False)