In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
rb_19 = pd.read_csv('FantasyPros_Fantasy_Football_Statistics_RB_19.csv')
wr_19 = pd.read_csv('FantasyPros_Fantasy_Football_Statistics_WR_19.csv')
qb_19 = pd.read_csv('FantasyPros_Fantasy_Football_Statistics_QB_19.csv')
te_19 = pd.read_csv('FantasyPros_Fantasy_Football_Statistics_TE_19.csv')
k_19 = pd.read_csv('FantasyPros_Fantasy_Football_Statistics_K_19.csv')
def_19 = pd.read_csv('FantasyPros_Fantasy_Football_Statistics_DST_19.csv')

In [3]:
concat_19 = pd.concat([rb_19, wr_19, te_19, k_19, qb_19, def_19])

In [4]:
concat_19.shape

(1246, 38)

In [5]:
concat_19.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,CMP,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD
0,1.0,Christian McCaffrey (CAR),287.0,"1,387",4.8,84.0,6.0,15.0,116.0,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Aaron Jones (GB),236.0,"1,084",4.6,56.0,5.0,16.0,49.0,68.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Derrick Henry (TEN),303.0,"1,540",5.1,74.0,9.0,16.0,18.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Ezekiel Elliott (DAL),301.0,"1,357",4.5,33.0,4.0,12.0,54.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Dalvin Cook (MIN),250.0,"1,135",4.5,75.0,7.0,13.0,53.0,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
concat_19.columns

Index(['Rank', 'Player', 'ATT', 'YDS', 'Y/A', 'LG', '20+', 'TD', 'REC', 'TGT',
       'YDS.1', 'Y/R', 'TD.1', 'FL', 'G', 'FPTS', 'FPTS/G', 'OWN', 'FG', 'FGA',
       'PCT', '1-19', '20-29', '30-39', '40-49', '50+', 'XPT', 'XPA', 'CMP',
       'INT', 'SACKS', 'ATT.1', 'SACK', 'FR', 'FF', 'DEF TD', 'SFTY',
       'SPC TD'],
      dtype='object')

In [7]:
concat_19['FantasyPointsRank'] = concat_19['FPTS'].rank(ascending = False)
concat_19 = concat_19.sort_values(by = 'FantasyPointsRank')

In [8]:
concat_19.shape

(1246, 39)

In [9]:
concat_19.head(10)

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,...,INT,SACKS,ATT.1,SACK,FR,FF,DEF TD,SFTY,SPC TD,FantasyPointsRank
0,1.0,Lamar Jackson (BAL),401.0,"3,127",7.8,NaN,NaN,36.0,NaN,NaN,...,6.0,23.0,176.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
0,1.0,Christian McCaffrey (CAR),287.0,"1,387",4.8,84.0,6.0,15.0,116.0,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
1,2.0,Dak Prescott (DAL),596.0,"4,902",8.2,NaN,NaN,30.0,NaN,NaN,...,11.0,23.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
2,3.0,Jameis Winston (NO),626.0,"5,109",8.2,NaN,NaN,33.0,NaN,NaN,...,30.0,47.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
3,4.0,Russell Wilson (SEA),516.0,"4,110",8.0,NaN,NaN,31.0,NaN,NaN,...,5.0,48.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0
4,5.0,Deshaun Watson (HOU),495.0,"3,852",7.8,NaN,NaN,26.0,NaN,NaN,...,12.0,44.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
0,1.0,Michael Thomas (NO),1.0,"1,725",NaN,49.0,17.0,9.0,149.0,185.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
5,6.0,Josh Allen (BUF),461.0,"3,089",6.7,NaN,NaN,20.0,NaN,NaN,...,9.0,38.0,109.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0
6,7.0,Kyler Murray (ARI),542.0,"3,722",6.9,NaN,NaN,20.0,NaN,NaN,...,12.0,48.0,93.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0
7,8.0,Patrick Mahomes II (KC),484.0,"4,031",8.3,NaN,NaN,26.0,NaN,NaN,...,5.0,17.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0

In [10]:
concat_19.to_csv('fp_data_uncleaned.csv', index = False)